package br.com.cuidaplus.api.care_task;

public enum TaskAuditAction {
  CRIADA, ALTERADA, PAUSADA, REATIVADA, CANCELADA,
  OCORRENCIA_ALTERADA, OCORRENCIA_CANCELADA, OCORRENCIA_CONCLUIDA, OCORRENCIA_NAO_REALIZADA
}
