package br.com.cuidaplus.api.care_task;

public enum TaskAuditAction {
  CRIADA, ALTERADA, PAUSADA, REATIVADA, CANCELADA,
  OCORRENCIA_ALTERADA, OCORRENCIA_CANCELADA, OCORRENCIA_CONCLUIDA, OCORRENCIA_NAO_REALIZADA,
  OCORRENCIA_NAO_REALIZADA_AUTOMATICAMENTE, FOTO_ANEXADA, NOTIFICACAO_INTERNA_CRIADA, LEMBRETE_CANCELADO
}
