export type AccountStatus = 'ATIVO' | 'BLOQUEADO' | 'INATIVO';
export type CaregiverApprovalStatus = 'PENDENTE' | 'APROVADO' | 'REPROVADO' | 'BLOQUEADO';
export type ResponsibleApprovalStatus = 'PENDENTE' | 'APROVADO' | 'REPROVADO' | 'BLOQUEADO';
export type AdminDashboardSummary = { pendingCaregivers:number; pendingResponsibles:number; totalUsers:number;
  blockedUsers:number; recentApprovals:number };

export type AdminUserSummary = { id:string; name:string; email:string; profileType:string; profileLabel:string;
  accountStatus:AccountStatus; accountStatusLabel:string; caregiverApprovalStatus?:CaregiverApprovalStatus|null;
  caregiverApprovalStatusLabel?:string|null; responsibleApprovalStatus?:ResponsibleApprovalStatus|null;
  responsibleApprovalStatusLabel?:string|null; createdAt:string };
export type AdminUserPage = { content:AdminUserSummary[]; page:number; size:number; totalElements:number; totalPages:number };
export type AdminHistoryItem = { previousStatus?:CaregiverApprovalStatus|null; newStatus:CaregiverApprovalStatus;
  newStatusLabel:string; reason?:string|null; administratorId:string; administratorName:string; createdAt:string };
export type AdminCaregiverDetails = { id:string; userId:string; name:string; email:string; cpf:string; phone?:string|null;
  profilePhotoUrl?:string|null; biography?:string|null; experience?:string|null; formations:string[]; otherFormation?:string|null;
  modalities:string[]; otherModality?:string|null; services:string[]; otherService?:string|null; city?:string|null;
  neighborhood?:string|null; state?:string|null; availabilityDays:string[]; availabilityPeriods:string[];
  availabilityStart?:string|null; availabilityEnd?:string|null; availabilityNotes?:string|null;
  status:CaregiverApprovalStatus; statusLabel:string;
  rejectionReason?:string|null; professionalBlockReason?:string|null; analyzedAt?:string|null; createdAt:string; history:AdminHistoryItem[] };
export type AdminUserDetails = { id:string; name:string; email:string; cpf:string; phone?:string|null; birthDate:string;
  profileType:string; profileLabel:string; accountStatus:AccountStatus; accountStatusLabel:string; accountBlockReason?:string|null;
  blockedAt?:string|null; unblockedAt?:string|null; lastLoginAt?:string|null; createdAt:string;
  caregiver?:AdminCaregiverDetails|null; responsible?:AdminResponsibleDetails|null };
export type AdminCaregiverSummary = { id:string; userId:string; name:string; email:string; city?:string|null;
  experience?:string|null; formations:string[]; status:CaregiverApprovalStatus; statusLabel:string; createdAt:string };
export type AdminCaregiverPage = { content:AdminCaregiverSummary[]; page:number; size:number; totalElements:number; totalPages:number };
export type AdminResponsibleHistoryItem = { previousStatus?:ResponsibleApprovalStatus|null; newStatus:ResponsibleApprovalStatus;
  newStatusLabel:string; reason?:string|null; administratorId:string; administratorName:string; createdAt:string };
export type AdminResponsibleDetails = { id:string; userId:string; name:string; email:string; cpf:string; phone?:string|null;
  relationship:string; otherRelationship?:string|null; contactPreference:string; status:ResponsibleApprovalStatus;
  statusLabel:string; rejectionReason?:string|null; blockReason?:string|null; analyzedAt?:string|null; createdAt:string;
  history:AdminResponsibleHistoryItem[] };
export type AdminResponsibleSummary = { id:string; userId:string; name:string; email:string; relationship:string;
  status:ResponsibleApprovalStatus; statusLabel:string; createdAt:string };
export type AdminResponsiblePage = { content:AdminResponsibleSummary[]; page:number; size:number; totalElements:number; totalPages:number };
