package br.com.cuidaplus.api.audit;

public enum AuditAction {
  LOGIN_SUCESSO("Login realizado"),
  LOGIN_BLOQUEADO("Login bloqueado"),
  RECUPERACAO_SENHA_SOLICITADA("Recuperação de senha solicitada"),
  SENHA_REDEFINIDA("Senha redefinida"),
  REAUTENTICACAO_EXCLUSAO("Identidade confirmada para exclusão"),
  CONTA_EXCLUSAO_SOLICITADA("Exclusão de conta solicitada"),
  CONTA_EXCLUIDA("Conta excluída"),
  DADOS_ANONIMIZADOS("Dados anonimizados"),
  SESSOES_REVOGADAS("Sessões e tokens revogados"),
  CONSULTA_USUARIO("Detalhes de usuário consultados"),
  CONSULTA_CUIDADOR("Detalhes de cuidador consultados"),
  CONSULTA_RESPONSAVEL("Detalhes de responsável consultados"),
  USUARIO_BLOQUEADO("Usuário bloqueado"),
  USUARIO_DESBLOQUEADO("Usuário desbloqueado"),
  CUIDADOR_APROVADO("Cuidador aprovado"),
  CUIDADOR_REPROVADO("Cuidador reprovado"),
  CUIDADOR_BLOQUEADO("Cuidador bloqueado"),
  RESPONSAVEL_APROVADO("Responsável aprovado"),
  RESPONSAVEL_REPROVADO("Responsável reprovado"),
  RESPONSAVEL_BLOQUEADO("Responsável bloqueado"),
  SOLICITACAO_SERVICO_CRIADA("Solicitação de serviço criada"),
  SOLICITACAO_SERVICO_ACEITA("Solicitação de serviço aceita"),
  SOLICITACAO_SERVICO_REJEITADA("Solicitação de serviço rejeitada"),
  SOLICITACAO_SERVICO_CANCELADA("Solicitação de serviço cancelada"),
  SOLICITACAO_SERVICO_EXPIRADA("Solicitação de serviço expirada"),
  CONTRATACAO_CRIADA("Contratação criada"),
  CONTRATACAO_ENCERRAMENTO_AGENDADO("Encerramento de contratação agendado"),
  CONTRATACAO_ENCERRADA("Contratação encerrada"),
  CONTRATACAO_CANCELADA("Contratação cancelada"),
  CONTRATACAO_STATUS_ALTERADO("Situação da contratação alterada"),
  ROTINA_CUIDADO_CRIADA("Rotina de cuidado criada"),
  ROTINA_CUIDADO_ALTERADA("Rotina de cuidado alterada"),
  ROTINA_CUIDADO_INATIVADA("Rotina de cuidado inativada"),
  ROTINA_CUIDADO_REATIVADA("Rotina de cuidado reativada"),
  TAREFA_CUIDADO_CRIADA("Tarefa de cuidado criada"),
  TAREFA_CUIDADO_ALTERADA("Tarefa de cuidado alterada"),
  TAREFA_CUIDADO_INATIVADA("Tarefa de cuidado inativada"),
  TAREFA_CUIDADO_REATIVADA("Tarefa de cuidado reativada"),
  OCORRENCIA_CUIDADO_ALTERADA("Ocorrência de cuidado alterada"),
  OCORRENCIA_CUIDADO_CANCELADA("Ocorrência de cuidado cancelada"),
  OCORRENCIA_CUIDADO_CONCLUIDA("Ocorrência de cuidado concluída"),
  OCORRENCIA_CUIDADO_NAO_REALIZADA("Ocorrência de cuidado não realizada"),
  REGISTRO_DIARIO_CRIADO("Registro de diário criado"),
  FOTO_ASSISTENCIAL_ENVIADA("Foto assistencial enviada"),
  PERFIL_ALTERADO("Perfil alterado"),
  ATENDIMENTO_INICIADO("Atendimento iniciado"),
  ATENDIMENTO_ENCERRADO("Atendimento encerrado"),
  RELATORIO_GERADO("Relatório gerado"),
  RELATORIO_EDITADO("Relatório editado"),
  RELATORIO_FINALIZADO("Relatório finalizado"),
  RELATORIO_EMAIL_ENVIADO("Relatório enviado por e-mail"),
  RELATORIO_EMAIL_FALHOU("Falha no envio do relatório por e-mail");

  private final String label;
  AuditAction(String label) { this.label = label; }
  public String getLabel() { return label; }
}

