package br.com.cuidaplus.api.profile;

public enum ServicoOferecido {
  HIGIENE_PESSOAL,
  BANHO,
  ALIMENTACAO,
  LOCOMOCAO,
  COMPANHIA,
  MEDICACAO_ORIENTADA,
  CONSULTAS,
  ATIVIDADES_DOMESTICAS_LEVES,
  MONITORAMENTO_NOTURNO,
  OUTRO
}
