import { useCallback, useState } from 'react';
import { router, useFocusEffect, useLocalSearchParams, type Href } from 'expo-router';
import { Alert, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { TaskPriorityBadge, TaskStatusBadge } from '@/components/task-badges';
import { useAuth } from '@/hooks/useAuth';
import { ApiError } from '@/services/api';
import { cancelTaskOccurrence, completeTaskOccurrence, getCaregiverOccurrence, getResponsibleOccurrence, markTaskOccurrenceNotCompleted } from '@/services/careTaskService';
import { colors, fontFamily, radii, shadows, spacing } from '@/theme/tokens';
import type { TaskOccurrence } from '@/types/careTasks';
import { medicationRouteLabels, medicationUnitLabels, taskCategoryName } from '@/utils/careTaskLabels';
import { formatDateBR, formatDateTimeLocal, formatScheduleTime } from '@/utils/dateTime';

export default function TaskOccurrenceDetailsScreen(){const params=useLocalSearchParams<{id:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const {user}=useAuth();const caregiver=user?.userType==='caregiver';const [item,setItem]=useState<TaskOccurrence>();const [error,setError]=useState(false);const [busy,setBusy]=useState(false);const [modal,setModal]=useState<'complete'|'not-completed'>();const [note,setNote]=useState('');const [reason,setReason]=useState('');
 const load=useCallback(async()=>{if(!id)return;setError(false);try{setItem(await(caregiver?getCaregiverOccurrence(id):getResponsibleOccurrence(id)));}catch{setError(true);}},[caregiver,id]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function complete(){if(!item)return;setBusy(true);try{setItem(await completeTaskOccurrence(item.id,item.version,note.trim()||undefined));setModal(undefined);Alert.alert('Tarefa concluída','O registro de atividade foi criado com sucesso.');}catch(e){Alert.alert('Não foi possível concluir',e instanceof ApiError?e.message:'Tente novamente.');}finally{setBusy(false);}}
 async function notCompleted(){if(!item)return;if(!reason.trim()){Alert.alert('Justificativa obrigatória','Informe por que a tarefa não foi realizada.');return;}setBusy(true);try{setItem(await markTaskOccurrenceNotCompleted(item.id,item.version,reason.trim(),note.trim()||undefined));setModal(undefined);Alert.alert('Situação atualizada','A tarefa foi marcada como não realizada.');}catch(e){Alert.alert('Não foi possível atualizar',e instanceof ApiError?e.message:'Tente novamente.');}finally{setBusy(false);}}
 function cancel(){if(!item)return;Alert.alert('Cancelar ocorrência?','Somente esta ocorrência será cancelada.',[{text:'Voltar',style:'cancel'},{text:'Cancelar',style:'destructive',onPress:async()=>{setBusy(true);try{setItem(await cancelTaskOccurrence(item.id,item.version));}catch(e){Alert.alert('Não foi possível cancelar',e instanceof ApiError?e.message:'Tente novamente.');}finally{setBusy(false);}}}]);}
 if(error)return <ScreenContainer contentStyle={styles.center}><Text style={styles.error}>Não foi possível carregar a ocorrência.</Text><PrimaryButton label="Voltar" variant="secondary" onPress={()=>router.back()}/></ScreenContainer>;if(!item)return <ScreenContainer contentStyle={styles.center}><Text style={styles.muted}>Carregando ocorrência...</Text></ScreenContainer>;const actionable=caregiver&&(item.status==='PENDENTE'||item.status==='ATRASADA');
 return <ScreenContainer contentStyle={styles.content}><AppHeader showBack backDisabled={busy} title="Detalhes da tarefa" subtitle={item.title}/><View style={styles.badges}><TaskStatusBadge status={item.status}/><TaskPriorityBadge priority={item.priority}/></View><Section title="Ocorrência"><Info label="Data" value={formatDateBR(item.scheduledDate)}/><Info label="Horário previsto" value={formatScheduleTime(item.scheduledTime)}/><Info label="Categoria" value={taskCategoryName(item.category,item.customCategory)}/><Info label="Pessoa assistida" value={item.assistedPersonName}/><Info label="Responsável" value={item.responsibleName}/><Info label="Cuidador(a)" value={item.caregiverName}/>{item.description?<Info label="Instruções" value={item.description}/>:null}{item.taskNotes?<Info label="Observações" value={item.taskNotes}/>:null}</Section>
 {item.medication?<Section title="Medicação"><View style={styles.notice}><Text style={styles.noticeText}>As informações sobre medicamentos são cadastradas pelos usuários e não representam prescrição ou orientação médica fornecida pelo Cuidar+.</Text></View><Info label="Medicamento" value={item.medication.name}/><Info label="Dosagem" value={`${item.medication.dosage} · ${item.medication.unit==='PERSONALIZADA'?item.medication.customUnit:medicationUnitLabels[item.medication.unit]}`}/><Info label="Administração" value={item.medication.administrationRoute==='OUTRA'?item.medication.customAdministrationRoute??'Outra':medicationRouteLabels[item.medication.administrationRoute]}/>{item.medication.additionalInstructions?<Info label="Orientações" value={item.medication.additionalInstructions}/>:null}</Section>:null}
 {item.completedAt||item.nonCompletionReason||item.executionNote?<Section title="Execução">{item.completedAt?<Info label="Concluída em" value={formatDateTimeLocal(item.completedAt)}/>:null}{item.executedByName?<Info label="Registrada por" value={item.executedByName}/>:null}{item.nonCompletionReason?<Info label="Justificativa" value={item.nonCompletionReason}/>:null}{item.executionNote?<Info label="Observação" value={item.executionNote}/>:null}{item.activityRecordId?<Info label="Registro de atividade" value="Criado e vinculado"/>:null}</Section>:null}
 {actionable?<Section title="Registrar execução"><PrimaryButton label="Marcar como concluída" disabled={busy} onPress={()=>{setNote('');setModal('complete');}}/><PrimaryButton label="Marcar como não realizada" variant="secondary" disabled={busy} onPress={()=>{setReason('');setNote('');setModal('not-completed');}}/></Section>:null}
 {!caregiver&&(item.status==='PENDENTE'||item.status==='ATRASADA')?<Section title="Gerenciar ocorrência"><PrimaryButton label="Editar esta ocorrência" variant="secondary" disabled={busy} onPress={()=>router.push(`/care-task-form?id=${item.taskId}&occurrenceId=${item.id}&occurrenceVersion=${item.version}&scheduledDate=${item.scheduledDate}&scheduledTime=${item.scheduledTime}` as Href)}/><PrimaryButton label="Cancelar esta ocorrência" variant="secondary" disabled={busy} onPress={cancel}/></Section>:null}
 <Modal transparent animationType="fade" visible={Boolean(modal)} onRequestClose={()=>!busy&&setModal(undefined)}><View style={styles.backdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>{modal==='complete'?'Concluir tarefa':'Marcar como não realizada'}</Text>{modal==='not-completed'?<AppTextInput label="Justificativa" required value={reason} onChangeText={setReason} multiline maxLength={1000}/>:null}<AppTextInput label="Observação da execução" optional value={note} onChangeText={setNote} multiline maxLength={1000}/><View style={styles.actions}><Pressable disabled={busy} onPress={()=>setModal(undefined)} style={styles.modalButton}><Text style={styles.cancelText}>Voltar</Text></Pressable><PrimaryButton label="Confirmar" loading={busy} disabled={busy} onPress={()=>void(modal==='complete'?complete():notCompleted())} style={styles.flex}/></View></View></View></Modal>
 </ScreenContainer>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},error:{fontFamily:fontFamily.bold,color:colors.destructive},muted:{fontFamily:fontFamily.medium,color:colors.mutedForeground},badges:{flexDirection:'row',gap:spacing.sm},section:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:17,color:colors.foreground},info:{gap:spacing.xxs},infoLabel:{fontFamily:fontFamily.semiBold,fontSize:11,color:colors.mutedForeground},infoValue:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:20,color:colors.foreground},notice:{padding:spacing.md,borderRadius:radii.lg,backgroundColor:'#FFF9E5'},noticeText:{fontFamily:fontFamily.medium,fontSize:12,lineHeight:19,color:'#665423'},backdrop:{flex:1,justifyContent:'center',padding:spacing.xl,backgroundColor:'rgba(27,45,64,0.4)'},modalCard:{gap:spacing.lg,padding:spacing.lg,borderRadius:radii.xl,backgroundColor:colors.card,...shadows.soft},modalTitle:{fontFamily:fontFamily.extraBold,fontSize:18,color:colors.foreground},actions:{flexDirection:'row',alignItems:'center',gap:spacing.sm},modalButton:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center'},cancelText:{fontFamily:fontFamily.bold,color:colors.primary},flex:{flex:1}});
