import { useCallback, useState } from 'react';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Camera, ImagePlus, Trash2 } from 'lucide-react-native';
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { TaskPriorityBadge, TaskStatusBadge } from '@/components/task-badges';
import { CarePhoto } from '@/components/care-photo';
import { useAuth } from '@/hooks/useAuth';
import { ApiError } from '@/services/api';
import { completeTaskOccurrence, getCaregiverOccurrence, getResponsibleCareOccurrence, markTaskOccurrenceNotCompleted } from '@/services/careTaskService';
import { colors, fontFamily, radii, shadows, spacing } from '@/theme/tokens';
import type { CareCompletionPhoto, TaskOccurrence } from '@/types/careTasks';
import { medicationRouteLabels, medicationUnitLabels, taskCategoryName } from '@/utils/careTaskLabels';
import { formatDateBR, formatDateTimeLocal, formatScheduleTime } from '@/utils/dateTime';

const MAX_PHOTOS=5;const MAX_PHOTO_SIZE=5*1024*1024;const SUPPORTED_TYPES=new Set(['image/jpeg','image/png','image/webp']);
export default function TaskOccurrenceDetailsScreen(){
  const params=useLocalSearchParams<{id:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const {user}=useAuth();const caregiver=user?.userType==='caregiver';
  const [item,setItem]=useState<TaskOccurrence>();const [error,setError]=useState(false);const [busy,setBusy]=useState(false);
  const [modal,setModal]=useState<'complete'|'not-completed'>();const [note,setNote]=useState('');const [reason,setReason]=useState('');const [photos,setPhotos]=useState<CareCompletionPhoto[]>([]);
  const load=useCallback(async()=>{if(!id)return;setError(false);try{setItem(await(caregiver?getCaregiverOccurrence(id):getResponsibleCareOccurrence(id)));}catch{setError(true);}},[caregiver,id]);
  useFocusEffect(useCallback(()=>{void load();},[load]));

  async function complete(){if(!item)return;if(item.requiresCompletionPhoto&&!photos.length){Alert.alert('Comprovação por foto','Adicione pelo menos uma foto para concluir este cuidado.');return;}setBusy(true);try{setItem(await completeTaskOccurrence(item.id,item.version,note.trim()||undefined,photos));setModal(undefined);setPhotos([]);Alert.alert('Cuidado concluído','O registro de atividade foi criado com sucesso.');}catch(cause){Alert.alert('Não foi possível concluir',cause instanceof ApiError?cause.message:'Tente novamente.');}finally{setBusy(false);}}
  async function notCompleted(){if(!item)return;if(!reason.trim()){Alert.alert('Justificativa obrigatória','Informe por que o cuidado não foi realizado.');return;}setBusy(true);try{setItem(await markTaskOccurrenceNotCompleted(item.id,item.version,reason.trim(),note.trim()||undefined));setModal(undefined);Alert.alert('Situação atualizada','O cuidado foi marcado como não realizado.');}catch(cause){Alert.alert('Não foi possível atualizar',cause instanceof ApiError?cause.message:'Tente novamente.');}finally{setBusy(false);}}
  function addAssets(assets:ImagePicker.ImagePickerAsset[]){
    const available=MAX_PHOTOS-photos.length;const selected=assets.slice(0,available);const invalid=selected.find(asset=>asset.fileSize&&asset.fileSize>MAX_PHOTO_SIZE||asset.mimeType&&!SUPPORTED_TYPES.has(asset.mimeType));
    if(invalid){Alert.alert('Foto inválida','Use imagens JPEG, PNG ou WebP com até 5 MB.');return;}
    const next=selected.map((asset,index)=>{const type=(asset.mimeType&&SUPPORTED_TYPES.has(asset.mimeType)?asset.mimeType:'image/jpeg') as CareCompletionPhoto['type'];const extension=type==='image/png'?'png':type==='image/webp'?'webp':'jpg';return{uri:asset.uri,name:asset.fileName??`comprovacao-${Date.now()}-${index}.${extension}`,type,file:asset.file};});
    setPhotos(current=>[...current,...next]);
  }
  async function takePhoto(){if(photos.length>=MAX_PHOTOS)return;const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){Alert.alert('Permissão necessária','Permita o acesso à câmera para tirar a foto.');return;}const result=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8,cameraType:ImagePicker.CameraType.back});if(!result.canceled)addAssets(result.assets);}
  async function choosePhotos(){if(photos.length>=MAX_PHOTOS)return;const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:MAX_PHOTOS-photos.length,quality:.8});if(!result.canceled)addAssets(result.assets);}
  if(error)return <ScreenContainer contentStyle={styles.center}><Text style={styles.error}>Não foi possível abrir este cuidado.</Text><PrimaryButton label="Voltar" variant="secondary" onPress={()=>router.back()}/></ScreenContainer>;
  if(!item)return <ScreenContainer contentStyle={styles.center}><Text style={styles.muted}>Carregando cuidado...</Text></ScreenContainer>;
  const today=todayInTimezone(item.timezone);const datePosition=item.scheduledDate===today?'today':item.scheduledDate<today?'past':'future';const pending=item.status==='PENDENTE'||item.status==='ATRASADA';const actionable=caregiver&&pending&&datePosition==='today';
  return <ScreenContainer contentStyle={styles.content}><AppHeader showBack backDisabled={busy} title="Detalhes do cuidado" subtitle={item.title}/><View style={styles.badges}><TaskStatusBadge status={item.status}/><TaskPriorityBadge priority={item.priority}/></View>
    <Section title="Cuidado"><Info label="Data" value={formatDateBR(item.scheduledDate)}/><Info label="Horário previsto" value={formatScheduleTime(item.scheduledTime)}/><Info label="Tipo de cuidado" value={taskCategoryName(item.category,item.customCategory)}/>{item.important?<Info label="Importância" value="Cuidado importante"/>:null}{item.description?<Info label="Instruções" value={item.description}/>:null}{item.taskNotes?<Info label="Observações" value={item.taskNotes}/>:null}</Section>
    <Section title="Lembretes internos"><Info label="Situação" value={item.reminderEnabled?'Ativados':'Desativados'}/>{item.reminderEnabled&&item.reminderMinutesBefore?<Info label="Antecedência" value={`${item.reminderMinutesBefore} minutos antes`}/>:null}{item.reminderEnabled&&item.reminderAtScheduledTime?<Info label="No horário previsto" value="Ativado"/>:null}{item.overdueReminderEnabled?<Info label="Aviso de atraso" value={`Após ${item.overdueAfterMinutes??0} minutos`}/>:null}{item.repeatWhilePending?<Info label="Repetição enquanto pendente" value={`A cada ${item.repeatIntervalMinutes??0} minutos`}/>:null}</Section>
    <Section title="Pessoa assistida"><Info label="Nome" value={item.assistedPersonName}/><Info label="Grau de dependência" value={item.dependencyLabel}/><Info label="Mobilidade" value={item.mobilityLabel}/></Section>
    <Section title="Contratação"><Info label="Tipo" value={item.hiringTypeLabel}/><Info label="Data de início" value={formatDateBR(item.contractStartDate)}/>{item.contractEndDate?<Info label="Data final" value={formatDateBR(item.contractEndDate)}/>:null}<Info label="Responsável" value={item.responsibleName}/><Info label="Cuidador(a)" value={item.caregiverName}/>{item.careAddress?<Info label="Endereço do cuidado" value={item.careAddress}/>:null}</Section>
    {item.medication?<Section title="Medicação"><View style={styles.notice}><Text style={styles.noticeText}>As informações sobre medicamentos são cadastradas pelos usuários e não representam prescrição ou orientação médica fornecida pelo Cuidar+.</Text></View><Info label="Medicamento" value={item.medication.name}/><Info label="Dosagem" value={`${item.medication.dosage} · ${item.medication.unit==='PERSONALIZADA'?item.medication.customUnit:medicationUnitLabels[item.medication.unit]}`}/><Info label="Administração" value={item.medication.administrationRoute==='OUTRA'?item.medication.customAdministrationRoute??'Outra':medicationRouteLabels[item.medication.administrationRoute]}/>{item.medication.additionalInstructions?<Info label="Orientações" value={item.medication.additionalInstructions}/>:null}</Section>:null}
    {item.completedAt||item.nonCompletionReason||item.executionNote||item.autoMarkedNotDone||item.photos?.length?<Section title="Execução">{item.completedAt?<Info label="Concluído em" value={formatDateTimeLocal(item.completedAt)}/>:null}{item.executedByName?<Info label="Registrado por" value={item.executedByName}/>:null}{item.autoMarkedNotDone?<Text style={styles.autoMessage}>Não realizado automaticamente, pois o dia previsto já passou.</Text>:null}{item.nonCompletionReason?<Info label="Justificativa" value={item.nonCompletionReason}/>:null}{item.executionNote?<Info label="Observação" value={item.executionNote}/>:null}{item.activityRecordId?<Info label="Registro de atividade" value="Criado e vinculado"/>:null}{item.photos?.length?<><Text style={styles.photoTitle}>Fotos de comprovação</Text><View style={styles.photoGrid}>{item.photos.map(photo=><CarePhoto key={photo.id} url={photo.url}/>)}</View></>:null}</Section>:null}
    {actionable?<Section title="Registrar execução"><PrimaryButton label="Marcar como concluído" disabled={busy} onPress={()=>{setNote('');setPhotos([]);setModal('complete');}}/><PrimaryButton label="Informar que não foi realizado" variant="secondary" disabled={busy} onPress={()=>{setReason('');setNote('');setModal('not-completed');}}/></Section>:null}
    {caregiver&&pending&&datePosition==='future'?<View style={styles.blocked}><Text style={styles.blockedText}>Este cuidado ainda não pode ser concluído.</Text></View>:null}
    {caregiver&&pending&&datePosition==='past'?<View style={styles.blocked}><Text style={styles.blockedText}>Este cuidado não foi realizado no dia previsto.</Text></View>:null}
    <Modal transparent animationType="fade" visible={Boolean(modal)} onRequestClose={()=>!busy&&setModal(undefined)}><View style={styles.backdrop}><View style={styles.modalCard}><ScrollView contentContainerStyle={styles.modalContent} keyboardShouldPersistTaps="handled"><Text style={styles.modalTitle}>{modal==='complete'?'Concluir cuidado':'Marcar como não realizado'}</Text>
      {modal==='complete'?<><View style={styles.photoHeading}><Text style={styles.photoTitle}>Comprovação por foto{item.requiresCompletionPhoto?' *':''}</Text><Text style={styles.photoHint}>{photos.length} de {MAX_PHOTOS} fotos</Text></View><Text style={styles.addPhotoLabel}>Adicionar foto</Text><View style={styles.pickerActions}><Pressable disabled={busy||photos.length>=MAX_PHOTOS} onPress={()=>void takePhoto()} style={styles.pickerButton}><Camera size={18} color={colors.primary}/><Text style={styles.pickerText}>Tirar foto</Text></Pressable><Pressable disabled={busy||photos.length>=MAX_PHOTOS} onPress={()=>void choosePhotos()} style={styles.pickerButton}><ImagePlus size={18} color={colors.primary}/><Text style={styles.pickerText}>Escolher da galeria</Text></Pressable></View>{photos.length?<View style={styles.photoGrid}>{photos.map((photo,index)=><View key={`${photo.uri}-${index}`} style={styles.previewWrap}><Image source={{uri:photo.uri}} style={styles.preview}/><Pressable accessibilityLabel="Remover foto" disabled={busy} onPress={()=>setPhotos(current=>current.filter((_,photoIndex)=>photoIndex!==index))} style={styles.removePhoto}><Trash2 size={16} color="#FFFFFF"/></Pressable></View>)}</View>:<Text style={styles.photoHint}>A foto é opcional, salvo quando exigida neste cuidado.</Text>}</>:null}
      {modal==='not-completed'?<AppTextInput label="Justificativa" required value={reason} onChangeText={setReason} multiline maxLength={1000}/>:null}<AppTextInput label="Observação (opcional)" value={note} onChangeText={setNote} multiline maxLength={1000}/><View style={styles.actions}><Pressable disabled={busy} onPress={()=>setModal(undefined)} style={styles.modalButton}><Text style={styles.cancelText}>Voltar</Text></Pressable><PrimaryButton label={modal==='complete'?'Concluir cuidado':'Confirmar'} loading={busy} disabled={busy} onPress={()=>void(modal==='complete'?complete():notCompleted())} style={styles.flex}/></View>
    </ScrollView></View></View></Modal>
  </ScreenContainer>;
}
function todayInTimezone(timezone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=(type:string)=>parts.find(part=>part.type===type)?.value??'';return `${value('year')}-${value('month')}-${value('day')}`;}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},error:{fontFamily:fontFamily.bold,color:colors.destructive},muted:{fontFamily:fontFamily.medium,color:colors.mutedForeground},badges:{flexDirection:'row',gap:spacing.sm},section:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:17,color:colors.foreground},info:{gap:spacing.xxs},infoLabel:{fontFamily:fontFamily.semiBold,fontSize:11,color:colors.mutedForeground},infoValue:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:20,color:colors.foreground},notice:{padding:spacing.md,borderRadius:radii.lg,backgroundColor:'#FFF9E5'},noticeText:{fontFamily:fontFamily.medium,fontSize:12,lineHeight:19,color:'#665423'},blocked:{padding:spacing.md,borderRadius:radii.lg,backgroundColor:'#FFF9E5'},blockedText:{fontFamily:fontFamily.semiBold,color:'#665423'},autoMessage:{fontFamily:fontFamily.semiBold,fontSize:13,lineHeight:20,color:colors.mutedForeground},backdrop:{flex:1,justifyContent:'center',padding:spacing.xl,backgroundColor:'rgba(27,45,64,0.4)'},modalCard:{maxHeight:'88%',borderRadius:radii.xl,backgroundColor:colors.card,...shadows.soft},modalContent:{gap:spacing.lg,padding:spacing.lg},modalTitle:{fontFamily:fontFamily.extraBold,fontSize:18,color:colors.foreground},actions:{flexDirection:'row',alignItems:'center',gap:spacing.sm},modalButton:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center'},cancelText:{fontFamily:fontFamily.bold,color:colors.primary},flex:{flex:1},photoHeading:{gap:spacing.xxs},photoTitle:{fontFamily:fontFamily.bold,fontSize:13,color:colors.foreground},addPhotoLabel:{fontFamily:fontFamily.semiBold,fontSize:12,color:colors.foreground},photoHint:{fontFamily:fontFamily.medium,fontSize:11,lineHeight:17,color:colors.mutedForeground},pickerActions:{flexDirection:'row',gap:spacing.sm},pickerButton:{flex:1,minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.xs,padding:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,backgroundColor:colors.secondary},pickerText:{fontFamily:fontFamily.bold,fontSize:11,color:colors.primary,textAlign:'center'},photoGrid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},previewWrap:{position:'relative'},preview:{width:84,height:84,borderRadius:radii.md,backgroundColor:colors.muted},savedPhoto:{width:96,height:96,borderRadius:radii.md,backgroundColor:colors.muted},removePhoto:{position:'absolute',top:4,right:4,width:28,height:28,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:'rgba(0,0,0,.65)'}});
