package br.com.cuidaplus.api.notification;
public enum NotificationType {
  SERVICE_REQUEST_CREATED, SERVICE_REQUEST_ACCEPTED, SERVICE_REQUEST_REJECTED, SERVICE_REQUEST_CANCELED, SERVICE_REQUEST_EXPIRED,
  CONTRACT_TERMINATION_SCHEDULED, CONTRACT_TERMINATED, CONTRACT_CANCELED_BEFORE_START, CONTRACT_AUTOMATICALLY_TERMINATED,
  CARE_TASK_CREATED, CARE_TASK_CANCELED, TASK_OCCURRENCE_COMPLETED, TASK_OCCURRENCE_NOT_COMPLETED
}
