package br.com.cuidaplus.api.notification;
public enum NotificationType {
  SERVICE_REQUEST_CREATED, SERVICE_REQUEST_ACCEPTED, SERVICE_REQUEST_REJECTED, SERVICE_REQUEST_CANCELED, SERVICE_REQUEST_EXPIRED,
  CONTRACT_TERMINATION_SCHEDULED, CONTRACT_TERMINATED, CONTRACT_CANCELED_BEFORE_START, CONTRACT_AUTOMATICALLY_TERMINATED,
  CARE_TASK_CREATED, CARE_TASK_CANCELED, TASK_OCCURRENCE_COMPLETED, TASK_OCCURRENCE_NOT_COMPLETED,
  CARE_TASK_REMINDER, CARE_TASK_OVERDUE, CARE_TASK_NOT_DONE, CARE_TASK_RESPONSIBLE_ALERT,
  CARE_OCCURRENCE_REMINDER, CARE_OCCURRENCE_OVERDUE, CARE_OCCURRENCE_NOT_DONE, CARE_OCCURRENCE_COMPLETED, CARE_OCCURRENCE_RESPONSIBLE_ALERT
}
