package br.com.cuidaplus.api.notification;
import br.com.cuidaplus.api.common.BusinessException; import br.com.cuidaplus.api.user.*; import java.time.Instant; import java.util.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class NotificationService{private final NotificationRepository repository;private final UserService users;private final NotificationPreferenceService preferences;private final ApplicationEventPublisher events;public NotificationService(NotificationRepository r,UserService u,NotificationPreferenceService p,ApplicationEventPublisher e){repository=r;users=u;preferences=p;events=e;}
 @Transactional public void create(User recipient,NotificationType type,String title,String message,UUID relatedId){create(recipient,type,title,message,RelatedEntityType.SERVICE_REQUEST,relatedId,null);}
 @Transactional public void create(User recipient,NotificationType type,String title,String message,RelatedEntityType entityType,UUID relatedId){create(recipient,type,title,message,entityType,relatedId,null);}
 @Transactional public void create(User recipient,NotificationType type,String title,String message,RelatedEntityType entityType,UUID relatedId,Instant scheduledAt){NotificationType canonicalType=NotificationCatalog.canonical(type);if(!preferences.isEnabled(recipient,canonicalType))return;String key=deduplicationKey(recipient,canonicalType,entityType,relatedId,scheduledAt);if(repository.existsByDeduplicationKey(key))return;Notification n=new Notification();n.setRecipient(recipient);n.setType(canonicalType);n.setTitle(title);n.setMessage(message);n.setRelatedEntityType(entityType);n.setRelatedEntityId(relatedId);n.setDeduplicationKey(key);repository.save(n);events.publishEvent(new NotificationCreatedEvent(n.getId(),recipient.getId(),canonicalType,title,entityType,relatedId));}
 @Transactional(readOnly=true) public List<NotificationResponse> list(UUID userId,int page,int size){List<Notification> all=repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(userId));int safeSize=Math.min(Math.max(size,1),50),from=Math.min(Math.max(page,0)*safeSize,all.size()),to=Math.min(from+safeSize,all.size());return all.subList(from,to).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public long unread(UUID id){return repository.countByRecipientAndReadAtIsNullAndClearedAtIsNull(users.findById(id));}
 @Transactional public NotificationResponse read(UUID uid,UUID id){Notification n=owned(uid,id);if(n.getReadAt()==null)n.setReadAt(Instant.now());return response(n);}
 @Transactional public void readAll(UUID uid){repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(uid)).forEach(n->{if(n.getReadAt()==null)n.setReadAt(Instant.now());});}
 @Transactional public void clear(UUID uid,UUID id){owned(uid,id).setClearedAt(Instant.now());}
 @Transactional public void clearAll(UUID uid){repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(uid)).forEach(n->n.setClearedAt(Instant.now()));}
 private String deduplicationKey(User recipient,NotificationType type,RelatedEntityType entityType,UUID relatedId,Instant scheduledAt){return recipient.getId()+"|"+type+"|"+entityType+"|"+relatedId+(scheduledAt==null?"":"|"+scheduledAt.toEpochMilli());}
 private Notification owned(UUID uid,UUID id){User u=users.findById(uid);return repository.findByIdAndRecipient(id,u).orElseThrow(()->new BusinessException("Notificação não encontrada.",HttpStatus.NOT_FOUND));}private NotificationResponse response(Notification n){return new NotificationResponse(n.getId(),n.getType(),n.getTitle(),n.getMessage(),n.getRelatedEntityType(),n.getRelatedEntityId(),n.getReadAt(),n.getCreatedAt());}}
