package br.com.cuidaplus.api.notification;
public enum NotificationType { SERVICE_REQUEST_CREATED, SERVICE_REQUEST_ACCEPTED, SERVICE_REQUEST_REJECTED, SERVICE_REQUEST_CANCELED, SERVICE_REQUEST_EXPIRED }
