package br.com.cuidaplus.api.notification;
import br.com.cuidaplus.api.common.BusinessException; import br.com.cuidaplus.api.user.*; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class NotificationService{private final NotificationRepository repository;private final UserService users;public NotificationService(NotificationRepository r,UserService u){repository=r;users=u;}
 @Transactional public void create(User recipient,NotificationType type,String title,String message,UUID relatedId){create(recipient,type,title,message,RelatedEntityType.SERVICE_REQUEST,relatedId);}
 @Transactional public void create(User recipient,NotificationType type,String title,String message,RelatedEntityType entityType,UUID relatedId){Notification n=new Notification();n.setRecipient(recipient);n.setType(type);n.setTitle(title);n.setMessage(message);n.setRelatedEntityType(entityType);n.setRelatedEntityId(relatedId);repository.save(n);}
 @Transactional(readOnly=true) public List<NotificationResponse> list(UUID userId,int page,int size){List<Notification> all=repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(userId));int safeSize=Math.min(Math.max(size,1),50),from=Math.min(Math.max(page,0)*safeSize,all.size()),to=Math.min(from+safeSize,all.size());return all.subList(from,to).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public long unread(UUID id){return repository.countByRecipientAndReadAtIsNullAndClearedAtIsNull(users.findById(id));}
 @Transactional public NotificationResponse read(UUID uid,UUID id){Notification n=owned(uid,id);if(n.getReadAt()==null)n.setReadAt(Instant.now());return response(n);}
 @Transactional public void readAll(UUID uid){repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(uid)).forEach(n->{if(n.getReadAt()==null)n.setReadAt(Instant.now());});}
 @Transactional public void clear(UUID uid,UUID id){owned(uid,id).setClearedAt(Instant.now());}
 @Transactional public void clearAll(UUID uid){repository.findByRecipientAndClearedAtIsNullOrderByCreatedAtDesc(users.findById(uid)).forEach(n->n.setClearedAt(Instant.now()));}
 private Notification owned(UUID uid,UUID id){User u=users.findById(uid);return repository.findByIdAndRecipient(id,u).orElseThrow(()->new BusinessException("Notificação não encontrada.",HttpStatus.NOT_FOUND));}private NotificationResponse response(Notification n){return new NotificationResponse(n.getId(),n.getType(),n.getTitle(),n.getMessage(),n.getRelatedEntityType(),n.getRelatedEntityId(),n.getReadAt(),n.getCreatedAt());}}
