import { useEffect, useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { AlertTriangle, MapPin } from 'lucide-react-native';
import { Alert, Modal, Pressable, StyleSheet, Text, View } from 'react-native';

import { AppHeader } from '@/components/app-header'; import { AppTextInput } from '@/components/app-text-input'; import { LoadingState } from '@/components/loading-state'; import { PrimaryButton } from '@/components/primary-button'; import { ScreenContainer } from '@/components/screen-container';
import { acceptServiceRequest, getReceivedServiceRequestDetails, rejectServiceRequest } from '@/services/receivedServiceRequestService'; import { ApiError } from '@/services/api';
import { colors, fontFamily, radii, shadows, spacing } from '@/theme/tokens'; import type { ReceivedServiceRequest } from '@/types/receivedServiceRequest'; import { activityLabels, hiringLabels, statusLabels, weekdayLabels } from '@/utils/serviceRequestLabels';
import { allergyOptions, contactPreferenceOptions, dependencyLevelOptions, foodRestrictionOptions, mobilityOptions, relationshipOptions } from '@/constants/enums';

const weekdayOrder = ['SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO'];
const optionLabel=(value:string|undefined|null,options:readonly {value:string;label:string}[])=>options.find((item)=>item.value===value)?.label??value??'Não informado';
const formatDate=(value:string)=>{const [year,month,day]=value.split('-');return day&&month&&year?`${day}/${month}/${year}`:value;};
const formatCep=(value:string)=>{const digits=value.replace(/\D/g,'');return digits.length===8?`${digits.slice(0,5)}-${digits.slice(5)}`:value;};
export default function CaregiverServiceRequestDetailsScreen(){
  const {id}=useLocalSearchParams<{id:string}>(); const [request,setRequest]=useState<ReceivedServiceRequest|null>(null); const [loading,setLoading]=useState(true); const [acceptVisible,setAcceptVisible]=useState(false); const [rejectVisible,setRejectVisible]=useState(false); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(id)getReceivedServiceRequestDetails(id).then(setRequest).finally(()=>setLoading(false));},[id]);
  if(loading)return <ScreenContainer contentStyle={styles.center}><LoadingState message="Carregando detalhes da solicitação..."/></ScreenContainer>;
  if(!request)return <ScreenContainer contentStyle={styles.center}><Text style={styles.empty}>Não foi possível carregar os detalhes da solicitação.</Text></ScreenContainer>;
  async function accept(){if(!request||busy)return;setBusy(true);try{setRequest(await acceptServiceRequest(request.id));setAcceptVisible(false);Alert.alert('Tudo certo','Solicitação aceita com sucesso.');}catch(error){Alert.alert('Não foi possível aceitar',error instanceof ApiError?error.message:'Não foi possível aceitar a solicitação. Tente novamente.');}finally{setBusy(false);}}
  async function reject(){if(!request||busy)return;setBusy(true);try{setRequest(await rejectServiceRequest(request.id,{reason:reason.trim()||undefined}));setRejectVisible(false);Alert.alert('Solicitação rejeitada','A solicitação foi marcada como rejeitada.');}catch(error){Alert.alert('Não foi possível rejeitar',error instanceof ApiError?error.message:'Não foi possível rejeitar a solicitação. Tente novamente.');}finally{setBusy(false);}}
  const schedule=[...request.scheduleDays].sort((a,b)=>weekdayOrder.indexOf(a.weekday)-weekdayOrder.indexOf(b.weekday));
  return <ScreenContainer contentStyle={styles.content}><AppHeader showBack title="Detalhes da solicitação"/>
    <Section title="Status da solicitação"><View style={[styles.status,request.status==='PENDENTE'&&styles.pending]}><Text style={styles.statusText}>{statusLabels[request.status]}</Text></View><Info label="Enviada em" value={new Date(request.createdAt).toLocaleString('pt-BR')}/>{request.status==='PENDENTE'?<Info label="Expira em" value={new Date(request.expiresAt).toLocaleDateString('pt-BR')}/>:null}</Section>
    {request.hasScheduleConflict?<View style={styles.conflict}><AlertTriangle color={colors.coral} size={22}/><View style={styles.flex}><Text style={styles.conflictTitle}>Possível conflito de horário</Text><Text style={styles.conflictText}>Esta solicitação possui horários que podem coincidir com outro serviço já aceito. Revise sua disponibilidade antes de aceitar.</Text></View></View>:null}
    <Section title="Dados do responsável"><Info label="Nome" value={request.responsible.name}/><Info label="Relação" value={optionLabel(request.responsible.relationship,relationshipOptions)}/><Info label="Preferência de contato" value={optionLabel(request.responsible.contactPreference,contactPreferenceOptions)}/></Section>
    <Section title="Pessoa assistida"><Info label="Nome e idade" value={`${request.assistedPerson.name} • ${request.assistedPerson.age} anos`}/><Info label="Dependência" value={optionLabel(request.assistedPerson.dependencyLevel,dependencyLevelOptions)}/><Info label="Mobilidade" value={optionLabel(request.assistedPerson.mobility,mobilityOptions)}/><Info label="Alergias" value={request.assistedPerson.allergies.map((item)=>optionLabel(item,allergyOptions)).join(', ')||'Não informadas'}/><Info label="Restrições alimentares" value={request.assistedPerson.foodRestrictions.map((item)=>optionLabel(item,foodRestrictionOptions)).join(', ')||'Não informadas'}/>{request.assistedPerson.medications?<Info label="Medicamentos e rotina" value={request.assistedPerson.medications}/>:null}{request.assistedPerson.notes?<Text style={styles.paragraph}>{request.assistedPerson.notes}</Text>:null}</Section>
    <Section title="Endereço do cuidado"><Info label="Endereço" value={`${request.careAddress.street}, ${request.careAddress.number}`}/>{request.careAddress.complement?<Info label="Complemento" value={request.careAddress.complement}/>:null}<Info label="Bairro" value={request.careAddress.neighborhood}/><Info label="Cidade" value={`${request.careAddress.city} - ${request.careAddress.state}`}/>{request.careAddress.cep?<Info label="CEP" value={formatCep(request.careAddress.cep)}/>:null}{request.careAddress.referencePoint?<Info label="Ponto de referência" value={request.careAddress.referencePoint}/>:null}{request.distanceKm!=null?<Info label="Distância aproximada" value={`${request.distanceKm.toFixed(1).replace('.',',')} km`}/>:null}<PrimaryButton label="Abrir no mapa" icon={MapPin} variant="secondary" onPress={()=>Alert.alert('Abrir no mapa','A localização será aberta no mapa em uma próxima etapa.')}/></Section>
    <Section title="Contratação"><Info label="Tipo" value={hiringLabels[request.hiringType]}/><Info label="Data de início" value={formatDate(request.startDate)}/>{request.endDate?<Info label="Data de término" value={formatDate(request.endDate)}/>:null}{request.specificDates.length?<Info label="Datas específicas" value={request.specificDates.map(formatDate).join(', ')}/>:null}</Section>
    <Section title="Dias e horários">{schedule.map((item)=><Text key={item.weekday} style={styles.schedule}>{weekdayLabels[item.weekday]} • {item.startTime.slice(0,5)} às {item.endTime.slice(0,5)}</Text>)}</Section>
    <Section title="Atividades solicitadas"><View style={styles.chips}>{request.activities.map((item)=><View key={item} style={styles.chip}><Text style={styles.chipText}>{activityLabels[item]}</Text></View>)}</View></Section>
    <Section title="Descrição das necessidades"><Text style={styles.paragraph}>{request.needsDescription}</Text></Section>
    {request.additionalNotes?<Section title="Observações adicionais"><Text style={styles.paragraph}>{request.additionalNotes}</Text></Section>:null}{request.negotiationNotes?<Section title="Negociação"><Text style={styles.paragraph}>{request.negotiationNotes}</Text></Section>:null}
    {request.status==='PENDENTE'?<View style={styles.actions}><PrimaryButton label="Aceitar solicitação" onPress={()=>setAcceptVisible(true)}/><PrimaryButton label="Rejeitar" variant="secondary" onPress={()=>setRejectVisible(true)}/></View>:<Text style={styles.responded}>Esta solicitação já foi respondida.</Text>}
    <DecisionModal visible={acceptVisible} title="Aceitar solicitação?" onClose={()=>setAcceptVisible(false)}><Text style={styles.paragraph}>Ao aceitar, esta solicitação será marcada como aceita e a contratação ficará agendada para a data prevista.</Text>{request.hasScheduleConflict?<Text style={styles.conflictText}>Há um possível conflito de horário. Confirme apenas se você tiver disponibilidade.</Text>:null}<PrimaryButton label="Confirmar aceite" onPress={accept} loading={busy}/></DecisionModal>
    <DecisionModal visible={rejectVisible} title="Rejeitar solicitação" onClose={()=>setRejectVisible(false)}><AppTextInput optional label="Motivo da rejeição" icon={AlertTriangle} placeholder="Informe o motivo, se desejar." value={reason} onChangeText={setReason} multiline numberOfLines={3}/><PrimaryButton label="Confirmar rejeição" onPress={reject} loading={busy}/></DecisionModal>
  </ScreenContainer>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
function DecisionModal({visible,title,onClose,children}:{visible:boolean;title:string;onClose:()=>void;children:React.ReactNode}){return <Modal transparent animationType="fade" visible={visible} onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.modal}><Text style={styles.modalTitle}>{title}</Text>{children}<Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>Cancelar</Text></Pressable></View></View></Modal>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,justifyContent:'center',padding:spacing.xl},empty:{textAlign:'center',fontFamily:fontFamily.medium,color:colors.mutedForeground},section:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,...shadows.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:17,color:colors.foreground},status:{alignSelf:'flex-start',paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radii.full,backgroundColor:colors.secondary},pending:{backgroundColor:colors.sunny},statusText:{fontFamily:fontFamily.bold,fontSize:12,color:colors.foreground},info:{gap:spacing.xxs},label:{fontFamily:fontFamily.semiBold,fontSize:11,color:colors.mutedForeground},value:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:19,color:colors.foreground},paragraph:{fontFamily:fontFamily.regular,fontSize:13,lineHeight:20,color:colors.mutedForeground},conflict:{flexDirection:'row',gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,backgroundColor:'#FFF1EB',borderWidth:1,borderColor:'#F3C8B8'},flex:{flex:1},conflictTitle:{fontFamily:fontFamily.bold,fontSize:14,color:colors.coral},conflictText:{fontFamily:fontFamily.medium,fontSize:12,lineHeight:18,color:colors.coral},schedule:{fontFamily:fontFamily.medium,fontSize:13,color:colors.foreground},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radii.full,backgroundColor:colors.secondary},chipText:{fontFamily:fontFamily.semiBold,fontSize:12,color:colors.primary},actions:{gap:spacing.md},responded:{textAlign:'center',fontFamily:fontFamily.semiBold,color:colors.mutedForeground},backdrop:{flex:1,justifyContent:'center',padding:spacing.xl,backgroundColor:'rgba(27,45,64,.38)'},modal:{gap:spacing.lg,padding:spacing.lg,borderRadius:radii.xl,backgroundColor:colors.card,...shadows.soft},modalTitle:{fontFamily:fontFamily.extraBold,fontSize:20,color:colors.foreground},cancel:{minHeight:44,alignItems:'center',justifyContent:'center'},cancelText:{fontFamily:fontFamily.semiBold,color:colors.mutedForeground}});
