package br.com.cuidaplus.api.config;

import java.util.Map;
import org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy;
import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.engine.jdbc.env.spi.JdbcEnvironment;

/**
 * Traduz os nomes físicos inferidos pelo Hibernate sem alterar os nomes das
 * propriedades Java nem o contrato JSON da API.
 */
public class PortuguesePhysicalNamingStrategy extends CamelCaseToUnderscoresNamingStrategy {

  private static final Map<String, String> NAMES = Map.ofEntries(
    // Tabelas
    Map.entry("users", "usuarios"),
    Map.entry("password_reset_tokens", "usuarios_tokens_redefinicao_senha"),
    Map.entry("responsible_profiles", "responsaveis"),
    Map.entry("caregiver_profiles", "cuidadores"),
    Map.entry("assisted_persons", "pessoas_assistidas"),
    Map.entry("emergency_contacts", "pessoas_assistidas_contatos_emergencia"),
    Map.entry("assisted_person_allergies", "pessoas_assistidas_alergias"),
    Map.entry("assisted_person_food_restrictions", "pessoas_assistidas_restricoes_alimentares"),
    Map.entry("caregiver_modalities", "cuidadores_modalidades"),
    Map.entry("caregiver_services", "cuidadores_servicos"),
    Map.entry("caregiver_availability_days", "cuidadores_disponibilidade_dias"),
    Map.entry("caregiver_availability_periods", "cuidadores_disponibilidade_periodos"),
    Map.entry("caregiver_formations", "cuidadores_formacoes"),
    Map.entry("service_requests", "solicitacoes_servico"),
    Map.entry("service_request_dates", "solicitacoes_servico_datas"),
    Map.entry("service_request_schedule_days", "solicitacoes_servico_agenda_dias"),
    Map.entry("service_request_activities", "solicitacoes_servico_atividades"),
    Map.entry("notifications", "notificacoes"),
    Map.entry("care_contracts", "contratacoes"),
    Map.entry("status_history", "solicitacoes_servico_contratacoes_historico_status"),
    Map.entry("care_tasks", "tarefas_cuidado"),
    Map.entry("care_task_weekdays", "tarefas_cuidado_dias_semana"),
    Map.entry("task_occurrences", "ocorrencias_cuidado"),
    Map.entry("care_activity_records", "registros_diario_cuidado"),
    Map.entry("care_task_audit", "tarefas_cuidado_auditoria"),
    Map.entry("care_routines", "rotinas_cuidado"),
    Map.entry("care_routine_items", "rotinas_cuidado_itens"),
    Map.entry("service_request_care_items_snapshot", "solicitacoes_servico_itens_cuidado_copias"),
    Map.entry("care_routine_item_weekdays", "rotinas_cuidado_itens_dias_semana"),
    Map.entry("service_request_care_snapshot_weekdays", "solicitacoes_servico_itens_cuidado_copias_dias_semana"),
    Map.entry("care_task_reminders", "ocorrencias_cuidado_lembretes"),
    Map.entry("care_occurrence_photos", "ocorrencias_cuidado_fotos"),
    Map.entry("user_notification_preferences", "notificacoes_preferencias"),
    Map.entry("service_attendance_records", "registros_atendimento"),
    Map.entry("attendance_reports", "relatorios_atendimento"),

    // Colunas inferidas ou declaradas pelas entidades
    Map.entry("full_name", "nome_completo"),
    Map.entry("password_hash", "senha_hash"),
    Map.entry("birth_date", "data_nascimento"),
    Map.entry("user_type", "tipo_usuario"),
    Map.entry("phone", "telefone"),
    Map.entry("profile_photo_url", "url_foto_perfil"),
    Map.entry("created_at", "criado_em"),
    Map.entry("updated_at", "atualizado_em"),
    Map.entry("user_id", "usuario_id"),
    Map.entry("token_hash", "hash_token"),
    Map.entry("expires_at", "expira_em"),
    Map.entry("used_at", "usado_em"),
    Map.entry("active", "ativo"),
    Map.entry("responsible_user_id", "usuario_responsavel_id"),
    Map.entry("caregiver_user_id", "usuario_cuidador_id"),
    Map.entry("assisted_person_id", "pessoa_assistida_id"),
    Map.entry("responsible_contact", "contato_responsavel"),
    Map.entry("caregiver_profile_id", "perfil_cuidador_id"),
    Map.entry("hiring_type", "tipo_contratacao"),
    Map.entry("start_date", "data_inicio"),
    Map.entry("end_date", "data_fim"),
    Map.entry("needs_description", "descricao_necessidades"),
    Map.entry("activity_other", "outra_atividade"),
    Map.entry("additional_notes", "observacoes_adicionais"),
    Map.entry("negotiation_notes", "observacoes_negociacao"),
    Map.entry("canceled_at", "cancelado_em"),
    Map.entry("rejection_reason", "motivo_rejeicao"),
    Map.entry("cancellation_reason", "motivo_cancelamento"),
    Map.entry("service_request_id", "solicitacao_servico_id"),
    Map.entry("service_date", "data_servico"),
    Map.entry("weekday", "dia_semana"),
    Map.entry("start_time", "horario_inicio"),
    Map.entry("end_time", "horario_fim"),
    Map.entry("activity", "atividade"),
    Map.entry("recipient_user_id", "usuario_destinatario_id"),
    Map.entry("type", "tipo"),
    Map.entry("title", "titulo"),
    Map.entry("message", "mensagem"),
    Map.entry("related_entity_type", "tipo_entidade_relacionada"),
    Map.entry("related_entity_id", "entidade_relacionada_id"),
    Map.entry("read_at", "lida_em"),
    Map.entry("cleared_at", "removida_em"),
    Map.entry("deduplication_key", "chave_deduplicacao"),
    Map.entry("contract_id", "contratacao_id"),
    Map.entry("caregiver_id", "cuidador_id"),
    Map.entry("responsible_id", "responsavel_id"),
    Map.entry("closure_reason", "motivo_encerramento"),
    Map.entry("termination_type", "tipo_encerramento"),
    Map.entry("termination_reason", "motivo_solicitacao_encerramento"),
    Map.entry("termination_notes", "observacoes_encerramento"),
    Map.entry("termination_requested_by_user_id", "usuario_solicitante_encerramento_id"),
    Map.entry("termination_requested_at", "encerramento_solicitado_em"),
    Map.entry("effective_end_date", "data_fim_efetiva"),
    Map.entry("cancellation_requested_by_user_id", "usuario_solicitante_cancelamento_id"),
    Map.entry("cancellation_requested_at", "cancelamento_solicitado_em"),
    Map.entry("entity_type", "tipo_entidade"),
    Map.entry("entity_id", "entidade_id"),
    Map.entry("previous_status", "status_anterior"),
    Map.entry("new_status", "novo_status"),
    Map.entry("changed_by_user_id", "usuario_alteracao_id"),
    Map.entry("reason", "motivo"),
    Map.entry("name", "nome"),
    Map.entry("description", "descricao"),
    Map.entry("care_routine_id", "rotina_cuidado_id"),
    Map.entry("sort_order", "ordem_exibicao"),
    Map.entry("category", "categoria"),
    Map.entry("custom_category", "categoria_personalizada"),
    Map.entry("priority", "prioridade"),
    Map.entry("recurrence_type", "tipo_recorrencia"),
    Map.entry("scheduled_time", "horario_previsto"),
    Map.entry("interval_days", "intervalo_dias"),
    Map.entry("reminder_enabled", "lembrete_habilitado"),
    Map.entry("reminder_minutes_before", "minutos_antecedencia_lembrete"),
    Map.entry("reminder_at_scheduled_time", "lembrar_no_horario_previsto"),
    Map.entry("overdue_reminder_enabled", "lembrete_atraso_habilitado"),
    Map.entry("overdue_after_minutes", "minutos_para_atraso"),
    Map.entry("repeat_while_pending", "repetir_enquanto_pendente"),
    Map.entry("repeat_interval_minutes", "intervalo_repeticao_minutos"),
    Map.entry("important", "importante"),
    Map.entry("notify_responsible_if_important", "notificar_responsavel_se_importante"),
    Map.entry("requires_completion_photo", "exige_foto_conclusao"),
    Map.entry("notes", "anotacoes"),
    Map.entry("care_routine_item_id", "item_rotina_cuidado_id"),
    Map.entry("care_routine_name_snapshot", "nome_rotina_snapshot"),
    Map.entry("original_care_routine_id", "rotina_cuidado_original_id"),
    Map.entry("original_care_routine_item_id", "item_rotina_cuidado_original_id"),
    Map.entry("snapshot_item_id", "item_snapshot_id"),
    Map.entry("task_id", "tarefa_id"),
    Map.entry("responsible_creator_id", "responsavel_criador_id"),
    Map.entry("caregiver_executor_id", "cuidador_executor_id"),
    Map.entry("previous_series_id", "serie_anterior_id"),
    Map.entry("source_snapshot_item_id", "item_snapshot_origem_id"),
    Map.entry("duplicate_of_task_id", "tarefa_duplicada_de_id"),
    Map.entry("medication_name", "nome_medicamento"),
    Map.entry("medication_dosage", "dosagem_medicamento"),
    Map.entry("medication_unit", "unidade_medicamento"),
    Map.entry("medication_custom_unit", "unidade_personalizada_medicamento"),
    Map.entry("medication_administration_route", "via_administracao_medicamento"),
    Map.entry("medication_custom_route", "via_personalizada_medicamento"),
    Map.entry("medication_instructions", "instrucoes_medicamento"),
    Map.entry("created_by_user_id", "usuario_criacao_id"),
    Map.entry("updated_by_user_id", "usuario_atualizacao_id"),
    Map.entry("version", "versao"),
    Map.entry("scheduled_date", "data_prevista"),
    Map.entry("scheduled_instant_utc", "instante_previsto_utc"),
    Map.entry("timezone", "fuso_horario"),
    Map.entry("completed_at", "concluido_em"),
    Map.entry("executed_by_user_id", "usuario_executor_id"),
    Map.entry("non_completion_reason", "motivo_nao_realizacao"),
    Map.entry("execution_note", "anotacao_execucao"),
    Map.entry("exception", "excecao"),
    Map.entry("auto_marked_not_done", "marcada_nao_realizada_automaticamente"),
    Map.entry("status_updated_at", "status_atualizado_em"),
    Map.entry("occurrence_id", "ocorrencia_id"),
    Map.entry("activity_type", "tipo_atividade"),
    Map.entry("source_type", "tipo_origem"),
    Map.entry("entry_date", "data_registro"),
    Map.entry("care_type", "tipo_cuidado"),
    Map.entry("occurred_at", "ocorrido_em"),
    Map.entry("activity_record_id", "registro_atividade_id"),
    Map.entry("actor_user_id", "usuario_ator_id"),
    Map.entry("action", "acao"),
    Map.entry("details", "detalhes"),
    Map.entry("uploaded_by_user_id", "usuario_envio_id"),
    Map.entry("file_name", "nome_arquivo"),
    Map.entry("original_file_name", "nome_arquivo_original"),
    Map.entry("content_type", "tipo_conteudo"),
    Map.entry("file_size", "tamanho_arquivo"),
    Map.entry("reminder_type", "tipo_lembrete"),
    Map.entry("scheduled_at", "previsto_em"),
    Map.entry("sent_at", "enviado_em"),
    Map.entry("notification_type", "tipo_notificacao"),
    Map.entry("enabled", "habilitado"),
    Map.entry("requester_user_id", "usuario_solicitante_id"),
    Map.entry("initiated_by", "iniciado_por"),
    Map.entry("source_opportunity_id", "oportunidade_origem_id"),
    Map.entry("attendance_date", "data_atendimento"),
    Map.entry("record_type", "tipo_registro"),
    Map.entry("recorded_at", "registrado_em"),
    Map.entry("accuracy", "precisao"),
    Map.entry("location_captured_at", "localizacao_capturada_em"),
    Map.entry("address_snapshot", "endereco_registrado"),
    Map.entry("device_timezone", "fuso_dispositivo"),
    Map.entry("scheduled_start_time", "horario_inicio_previsto"),
    Map.entry("scheduled_end_time", "horario_fim_previsto"),
    Map.entry("allowed_window_start", "janela_permitida_inicio"),
    Map.entry("allowed_window_end", "janela_permitida_fim"),
    Map.entry("within_allowed_window", "dentro_janela_permitida"),
    Map.entry("attendance_start_record_id", "registro_inicio_atendimento_id"),
    Map.entry("attendance_end_record_id", "registro_fim_atendimento_id"),
    Map.entry("generated_text", "texto_gerado"),
    Map.entry("edited_text", "texto_editado"),
    Map.entry("final_text", "texto_final"),
    Map.entry("nursing_notes", "anotacoes_enfermagem"),
    Map.entry("email_status", "status_email"),
    Map.entry("email_requested_at", "email_solicitado_em"),
    Map.entry("email_sent_at", "email_enviado_em"),
    Map.entry("email_attempts", "tentativas_email"),
    Map.entry("email_next_retry_at", "proxima_tentativa_email_em"),
    Map.entry("email_error_message", "mensagem_erro_email"),
    Map.entry("generated_at", "gerado_em"),
    Map.entry("edited_at", "editado_em"),
    Map.entry("finalized_at", "finalizado_em")
  );

  @Override
  public Identifier toPhysicalTableName(Identifier name, JdbcEnvironment jdbcEnvironment) {
    return translate(super.toPhysicalTableName(name, jdbcEnvironment));
  }

  @Override
  public Identifier toPhysicalSequenceName(Identifier name, JdbcEnvironment jdbcEnvironment) {
    return translate(super.toPhysicalSequenceName(name, jdbcEnvironment));
  }

  @Override
  public Identifier toPhysicalColumnName(Identifier name, JdbcEnvironment jdbcEnvironment) {
    return translate(super.toPhysicalColumnName(name, jdbcEnvironment));
  }

  private Identifier translate(Identifier identifier) {
    if (identifier == null) return null;
    String translated = NAMES.getOrDefault(identifier.getText(), identifier.getText());
    return Identifier.toIdentifier(translated, identifier.isQuoted());
  }
}
