import { Redirect, router, useFocusEffect, type Href } from 'expo-router';
import { Search, ShieldCheck, UserRound, UserRoundCheck } from 'lucide-react-native';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';

import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { LoadingState } from '@/components/loading-state';
import { ProfileAvatar } from '@/components/profile-avatar';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { useAuth } from '@/hooks/useAuth';
import * as admin from '@/services/adminService';
import { ApiError } from '@/services/api';
import type { AccountStatus, AdminCaregiverDetails, AdminCaregiverSummary, AdminResponsibleDetails, AdminResponsibleSummary, AdminUserDetails, AdminUserSummary, CaregiverApprovalStatus, ResponsibleApprovalStatus } from '@/types/admin';
import { caregiverEducationOptions, caregiverExperienceRangeOptions, caregiverServiceOptions, careModalityOptions, contactPreferenceOptions, dayPeriodOptions, relationshipOptions, weekDayOptions } from '@/constants/enums';
import { colors, fontFamily, radii, spacing } from '@/theme/tokens';

export type AdministrationArea='users'|'caregivers'|'responsibles';
const accountFilters:{value?:AccountStatus;label:string}[]=[{label:'Todas'},{value:'ATIVO',label:'Ativas'},{value:'BLOQUEADO',label:'Bloqueadas'},{value:'INATIVO',label:'Inativas'},{value:'EXCLUIDO',label:'Excluídas'}];
const approvalFilters:{value?:CaregiverApprovalStatus;label:string}[]=[{label:'Todos'},{value:'PENDENTE',label:'Pendentes'},{value:'APROVADO',label:'Aprovados'},{value:'REPROVADO',label:'Reprovados'},{value:'BLOQUEADO',label:'Bloqueados'}];
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Não informado';
const labelOf=(value:string|undefined|null,options:readonly {value:string;label:string}[])=>options.find(item=>item.value===value)?.label??'Não informado';
const labelsOf=(values:string[],options:readonly {value:string;label:string}[])=>values.map(value=>labelOf(value,options)).join(', ')||'Não informado';

export { CaregiverDetail, ResponsibleDetail };

export function AdministrationView({initialArea='users',areas=['users','caregivers','responsibles'],initialAccountStatus,initialApprovalStatus='PENDENTE'}:{initialArea?:AdministrationArea;areas?:AdministrationArea[];initialAccountStatus?:AccountStatus;initialApprovalStatus?:CaregiverApprovalStatus}){
  const {user,isLoading:isAuthLoading}=useAuth(); const [area,setArea]=useState<AdministrationArea>(initialArea); const [search,setSearch]=useState('');
  const [accountStatus,setAccountStatus]=useState<AccountStatus|undefined>(initialAccountStatus); const [approvalStatus,setApprovalStatus]=useState<CaregiverApprovalStatus|undefined>(initialApprovalStatus);
  const [users,setUsers]=useState<AdminUserSummary[]>([]); const [caregivers,setCaregivers]=useState<AdminCaregiverSummary[]>([]);
  const [responsibles,setResponsibles]=useState<AdminResponsibleSummary[]>([]);
  const [selectedUser,setSelectedUser]=useState<AdminUserDetails|null>(null);
  const [reason,setReason]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [feedback,setFeedback]=useState<string|null>(null);
  useEffect(()=>{setArea(initialArea);setSelectedUser(null);},[initialArea]);
  useEffect(()=>setAccountStatus(initialAccountStatus),[initialAccountStatus]);
  useEffect(()=>setApprovalStatus(initialApprovalStatus),[initialApprovalStatus]);
  useEffect(()=>{if(!isAuthLoading&&user?.userType!=='admin')router.replace('/(tabs)/inicio');},[isAuthLoading,user?.userType]);
  const load=useCallback(async()=>{if(user?.userType!=='admin')return;setLoading(true);setFeedback(null);try{if(area==='users'){const page=await admin.listUsers(search,accountStatus);setUsers(page.content);}else if(area==='caregivers'){const page=await admin.listCaregivers(search,approvalStatus);setCaregivers(page.content);}else{const page=await admin.listResponsibles(search,approvalStatus as ResponsibleApprovalStatus|undefined);setResponsibles(page.content);}}catch(error){if(__DEV__&&area!=='users'){console.warn('[AdminApprovals] Erro ao carregar aprovações',{profile:area,status:approvalStatus??null,httpStatus:error instanceof ApiError?error.status:undefined,code:error instanceof ApiError?error.code:undefined});}setFeedback(area==='caregivers'?'Não foi possível carregar os cuidadores para análise.':area==='responsibles'?'Não foi possível carregar os responsáveis para análise.':'Não foi possível carregar os usuários.');}finally{setLoading(false);}},[accountStatus,approvalStatus,area,search,user?.userType]);
  useFocusEffect(useCallback(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]));
  function openUser(id:string){router.push({pathname:'/admin/user/[userId]',params:{userId:id,from:'users',status:accountStatus??'ALL'}} as Href);}
  function openCaregiver(id:string){router.push({pathname:'/admin/caregiver/[caregiverId]',params:{caregiverId:id,from:'approvals',profile:area,status:approvalStatus??'ALL'}} as Href);}
  function openResponsible(id:string){router.push({pathname:'/admin/responsible/[responsibleId]',params:{responsibleId:id,from:'approvals',profile:area,status:approvalStatus??'ALL'}} as Href);}
  async function execute(action:()=>Promise<unknown>,success:string){setBusy(true);setFeedback(null);try{await action();setSelectedUser(null);setReason('');await load();Alert.alert('Tudo certo',success);}catch(error){setFeedback(error instanceof ApiError?error.message:'Não foi possível concluir a ação.');}finally{setBusy(false);}}
  function requireReason(action:()=>Promise<unknown>,message:string){if(!reason.trim()){setFeedback('Informe o motivo antes de continuar.');return;}Alert.alert('Confirmar ação',message,[{text:'Cancelar',style:'cancel'},{text:'Confirmar',style:'destructive',onPress:()=>void execute(action,'Situação atualizada com sucesso.')}]);}
  if(isAuthLoading||user?.userType!=='admin')return <ScreenContainer contentStyle={styles.content}><LoadingState message="Validando acesso administrativo..."/></ScreenContainer>;
  return <ScreenContainer contentStyle={[styles.content,{paddingBottom:spacing.xxxl}]} keyboardAvoiding>
    <AppHeader title={area==='users'?'Usuários':'Aprovações'} subtitle={area==='users'?'Consulte contas e controle o acesso ao sistema.':'Analise cadastros de cuidadores e responsáveis com segurança.'}/>
    {areas.length>1?<View style={styles.segment}>
      {areas.includes('users')?<Segment active={area==='users'} label="Usuários" icon={UserRound} onPress={()=>{setArea('users');setSelectedUser(null);}}/>:null}
      {areas.includes('caregivers')?<Segment active={area==='caregivers'} label="Cuidadores" icon={UserRoundCheck} onPress={()=>{setArea('caregivers');setSelectedUser(null);}}/>:null}
      {areas.includes('responsibles')?<Segment active={area==='responsibles'} label="Responsáveis" icon={ShieldCheck} onPress={()=>{setArea('responsibles');setSelectedUser(null);}}/>:null}
    </View>:null}
    <AppTextInput label="Pesquisar" icon={Search} placeholder="Nome ou e-mail" value={search} onChangeText={setSearch}/>
    <View style={styles.filters}>{(area==='users'?accountFilters:approvalFilters).map(item=><Chip key={item.label} label={item.label} active={area==='users'?accountStatus===item.value:approvalStatus===item.value} onPress={()=>area==='users'?setAccountStatus(item.value as AccountStatus|undefined):setApprovalStatus(item.value as CaregiverApprovalStatus|undefined)}/>)}</View>
    {feedback?<View style={{gap:spacing.md}}><Text style={styles.error}>{feedback}</Text><PrimaryButton label="Tentar novamente" variant="secondary" onPress={()=>void load()}/></View>:loading?<LoadingState message={area==='caregivers'?'Carregando cuidadores...':area==='responsibles'?'Carregando responsáveis...':'Carregando usuários...'}/>:area==='users'?users.length?users.map(item=><UserCard key={item.id} item={item} onPress={()=>void openUser(item.id)}/>):<Text style={styles.empty}>Nenhum usuário encontrado para este filtro.</Text>:area==='caregivers'?caregivers.length?caregivers.map(item=><CaregiverCard key={item.id} item={item} onPress={()=>void openCaregiver(item.id)}/>):<Text style={styles.empty}>Nenhum cuidador encontrado para este filtro.</Text>:responsibles.length?responsibles.map(item=><ResponsibleCard key={item.id} item={item} onPress={()=>void openResponsible(item.id)}/>):<Text style={styles.empty}>Nenhum responsável encontrado para este filtro.</Text>}
    {selectedUser?<View style={styles.detail}><Text style={styles.detailTitle}>Detalhes do usuário</Text><Info label="Nome" value={selectedUser.name}/><Info label="E-mail" value={selectedUser.email}/><Info label="Perfil" value={selectedUser.profileLabel}/><Info label="Situação da conta" value={selectedUser.accountStatusLabel}/><Info label="Último acesso" value={date(selectedUser.lastLoginAt)}/>{selectedUser.accountBlockReason?<Info label="Motivo do bloqueio" value={selectedUser.accountBlockReason}/>:null}{selectedUser.accountStatus==='BLOQUEADO'?<PrimaryButton label="Desbloquear usuário" loading={busy} onPress={()=>Alert.alert('Desbloquear usuário?','O acesso será restaurado somente se o cadastro do perfil também estiver aprovado.',[{text:'Cancelar',style:'cancel'},{text:'Desbloquear',onPress:()=>void execute(()=>admin.unblockUser(selectedUser.id),'Usuário desbloqueado com sucesso.')}])}/>:selectedUser.accountStatus==='ATIVO'&&selectedUser.id===user.id?<Text style={styles.empty}>Você não pode bloquear a própria conta administrativa.</Text>:selectedUser.accountStatus==='ATIVO'?<><AppTextInput label="Motivo do bloqueio" value={reason} onChangeText={setReason} multiline/><PrimaryButton label="Bloquear usuário" loading={busy} onPress={()=>requireReason(()=>admin.blockUser(selectedUser.id,reason.trim()),'O usuário perderá o acesso ao sistema.')}/></>:<Text style={styles.empty}>Contas inativas não possuem ações administrativas disponíveis.</Text>}<PrimaryButton label="Fechar detalhes" variant="secondary" onPress={()=>setSelectedUser(null)}/></View>:null}
  </ScreenContainer>;
}
export default function AdministrationScreen(){return <Redirect href="/admin/users"/>;}
function Segment({active,label,icon:Icon,onPress}:{active:boolean;label:string;icon:typeof ShieldCheck;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.segmentItem,active&&styles.segmentActive]}><Icon color={active?colors.primaryForeground:colors.primary} size={18}/><Text style={[styles.segmentText,active&&styles.segmentTextActive]}>{label}</Text></Pressable>}
function Chip({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>}
function Status({label}:{label:string}){return <View style={styles.status}><Text style={styles.statusText}>{label}</Text></View>}
function UserCard({item,onPress}:{item:AdminUserSummary;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.card}><View style={styles.row}><View style={styles.grow}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.email}</Text><Text style={styles.meta}>{item.profileLabel} • Cadastro em {date(item.createdAt)}</Text></View><Status label={item.accountStatusLabel}/></View>{item.caregiverApprovalStatusLabel?<Text style={styles.note}>Situação profissional: {item.caregiverApprovalStatusLabel}</Text>:null}{item.responsibleApprovalStatusLabel?<Text style={styles.note}>Situação do cadastro: {item.responsibleApprovalStatusLabel}</Text>:null}</Pressable>}
function CaregiverCard({item,onPress}:{item:AdminCaregiverSummary;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.card}><View style={styles.row}><View style={styles.grow}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.email}</Text><Text style={styles.meta}>Cadastro em {date(item.createdAt)} • {item.city??'Cidade não informada'}</Text><Text style={styles.meta}>Formação: {labelsOf(item.formations,caregiverEducationOptions)}</Text><Text style={styles.meta}>Experiência: {labelOf(item.experience,caregiverExperienceRangeOptions)}</Text></View><Status label={item.statusLabel}/></View><Text style={styles.note}>Ver detalhes</Text></Pressable>}
function ResponsibleCard({item,onPress}:{item:AdminResponsibleSummary;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.card}><View style={styles.row}><View style={styles.grow}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.email}</Text><Text style={styles.meta}>Vínculo: {labelOf(item.relationship,relationshipOptions)} • Cadastro em {date(item.createdAt)}</Text></View><Status label={item.statusLabel}/></View></Pressable>}
function Info({label,value}:{label:string;value?:string|null}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value||'Não informado'}</Text></View>}
function CaregiverDetail({value,reason,setReason,busy,close,approve,reject,block}:{value:AdminCaregiverDetails;reason:string;setReason:(v:string)=>void;busy:boolean;close:()=>void;approve:()=>void;reject:()=>void;block:()=>void}){const initials=value.name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();return <View style={styles.detail}><Text style={styles.detailTitle}>Cadastro profissional</Text><ProfileAvatar imageUrl={value.profilePhotoUrl} initials={initials} name={value.name} subtitle={value.email}/><Info label="Nome" value={value.name}/><Info label="E-mail" value={value.email}/><Info label="Telefone" value={value.phone}/><Info label="Localização" value={[value.neighborhood,value.city,value.state].filter(Boolean).join(', ')}/><Info label="Experiência" value={labelOf(value.experience,caregiverExperienceRangeOptions)}/><Info label="Formações" value={labelsOf(value.formations,caregiverEducationOptions)}/><Info label="Modalidades" value={labelsOf(value.modalities,careModalityOptions)}/><Info label="Serviços" value={labelsOf(value.services,caregiverServiceOptions)}/><Info label="Dias disponíveis" value={labelsOf(value.availabilityDays,weekDayOptions)}/><Info label="Períodos disponíveis" value={labelsOf(value.availabilityPeriods,dayPeriodOptions)}/><Info label="Horário personalizado" value={value.availabilityStart&&value.availabilityEnd?`${value.availabilityStart.slice(0,5)} às ${value.availabilityEnd.slice(0,5)}`:null}/><Info label="Observações de disponibilidade" value={value.availabilityNotes}/><Info label="Biografia" value={value.biography}/><Info label="Situação profissional" value={value.statusLabel}/>{value.rejectionReason?<Info label="Motivo da reprovação" value={value.rejectionReason}/>:null}{value.professionalBlockReason?<Info label="Motivo do bloqueio" value={value.professionalBlockReason}/>:null}{value.history.length?<View style={styles.history}><Text style={styles.infoLabel}>Histórico de análise</Text>{value.history.map((item,index)=><Text key={`${item.createdAt}-${index}`} style={styles.meta}>{item.newStatusLabel} em {date(item.createdAt)} por {item.administratorName}{item.reason?` — ${item.reason}`:''}</Text>)}</View>:null}{value.status==='PENDENTE'?<><AppTextInput label="Motivo da reprovação" value={reason} onChangeText={setReason} multiline/><PrimaryButton label="Aprovar cuidador" loading={busy} onPress={approve}/><PrimaryButton label="Reprovar cuidador" variant="secondary" disabled={busy} onPress={reject}/></>:value.status==='APROVADO'?<><AppTextInput label="Motivo do bloqueio" value={reason} onChangeText={setReason} multiline/><PrimaryButton label="Bloquear cuidador" variant="secondary" disabled={busy} onPress={block}/></>:<Text style={styles.empty}>{value.status==='REPROVADO'?'Este cadastro já foi reprovado.':'Este cuidador está bloqueado.'}</Text>}<PrimaryButton label="Fechar detalhes" variant="secondary" onPress={close}/></View>}
function ResponsibleDetail({value,reason,setReason,busy,close,approve,reject,block}:{value:AdminResponsibleDetails;reason:string;setReason:(v:string)=>void;busy:boolean;close:()=>void;approve:()=>void;reject:()=>void;block:()=>void}){return <View style={styles.detail}><Text style={styles.detailTitle}>Cadastro do responsável</Text><Info label="Nome" value={value.name}/><Info label="E-mail" value={value.email}/><Info label="Telefone" value={value.phone}/><Info label="Vínculo" value={value.otherRelationship||labelOf(value.relationship,relationshipOptions)}/><Info label="Preferência de contato" value={labelOf(value.contactPreference,contactPreferenceOptions)}/><Info label="Situação do cadastro" value={value.statusLabel}/>{value.rejectionReason?<Info label="Motivo da reprovação" value={value.rejectionReason}/>:null}{value.blockReason?<Info label="Motivo do bloqueio" value={value.blockReason}/>:null}{value.history.length?<View style={styles.history}><Text style={styles.infoLabel}>Histórico de análise</Text>{value.history.map((item,index)=><Text key={`${item.createdAt}-${index}`} style={styles.meta}>{item.newStatusLabel} em {date(item.createdAt)} por {item.administratorName}{item.reason?` — ${item.reason}`:''}</Text>)}</View>:null}{value.status==='PENDENTE'?<><AppTextInput label="Motivo da reprovação" value={reason} onChangeText={setReason} multiline/><PrimaryButton label="Aprovar responsável" loading={busy} onPress={approve}/><PrimaryButton label="Reprovar responsável" variant="secondary" disabled={busy} onPress={reject}/></>:value.status==='APROVADO'?<><AppTextInput label="Motivo do bloqueio" value={reason} onChangeText={setReason} multiline/><PrimaryButton label="Bloquear responsável" variant="secondary" disabled={busy} onPress={block}/></>:<Text style={styles.empty}>Este cadastro não possui ações disponíveis no estado atual.</Text>}<PrimaryButton label="Fechar detalhes" variant="secondary" onPress={close}/></View>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},segment:{flexDirection:'row',gap:spacing.sm,padding:spacing.xs,backgroundColor:colors.muted,borderRadius:radii.lg},segmentItem:{flex:1,minHeight:46,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm,borderRadius:radii.md},segmentActive:{backgroundColor:colors.primary},segmentText:{fontFamily:fontFamily.bold,fontSize:13,color:colors.primary},segmentTextActive:{color:colors.primaryForeground},filters:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radii.full,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},chipActive:{backgroundColor:colors.secondary,borderColor:colors.primary},chipText:{fontFamily:fontFamily.medium,fontSize:12,color:colors.mutedForeground},chipTextActive:{fontFamily:fontFamily.bold,color:colors.primary},card:{padding:spacing.lg,gap:spacing.sm,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},row:{flexDirection:'row',alignItems:'flex-start',gap:spacing.md},grow:{flex:1,gap:spacing.xxs},name:{fontFamily:fontFamily.bold,fontSize:15,color:colors.foreground},meta:{fontFamily:fontFamily.regular,fontSize:12,lineHeight:18,color:colors.mutedForeground},note:{fontFamily:fontFamily.medium,fontSize:12,color:colors.foreground},status:{paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radii.full,backgroundColor:colors.secondary},statusText:{fontFamily:fontFamily.bold,fontSize:11,color:colors.primary},detail:{padding:spacing.xl,gap:spacing.md,borderRadius:radii.xxl,borderWidth:1,borderColor:colors.primary,backgroundColor:colors.card},detailTitle:{fontFamily:fontFamily.extraBold,fontSize:20,color:colors.foreground},info:{gap:spacing.xxs},infoLabel:{fontFamily:fontFamily.bold,fontSize:12,color:colors.mutedForeground},infoValue:{fontFamily:fontFamily.medium,fontSize:14,lineHeight:21,color:colors.foreground},history:{gap:spacing.sm},error:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:20,color:colors.destructive},empty:{fontFamily:fontFamily.medium,fontSize:14,textAlign:'center',color:colors.mutedForeground,padding:spacing.xl}});
