import { useEffect, useState } from 'react';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { FileText, Trash2 } from 'lucide-react-native';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';

import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { OptionGroup } from '@/components/option-group';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { TimePickerField } from '@/components/time-picker-field';
import { ApiError } from '@/services/api';
import { createCareRoutine, getCareRoutine, getCareRoutineFormData, updateCareRoutine } from '@/services/careRoutineService';
import { colors, fontFamily, radii, spacing } from '@/theme/tokens';
import type { CareRoutineFormData, CareRoutineItem, CareRoutinePayload } from '@/types/careRoutine';
import type { MedicationAdministrationRoute, MedicationUnit, TaskCategory, TaskPriority, TaskRecurrenceType, TaskWeekday } from '@/types/careTasks';
import { medicationRouteLabels, medicationUnitLabels, taskCategoryLabels, taskPriorityLabels, taskWeekdayLabels } from '@/utils/careTaskLabels';

type DraftItem={key:string;title:string;description:string;category:TaskCategory;customCategory:string;priority:TaskPriority;recurrenceType:TaskRecurrenceType;scheduledTime:string;intervalDays:string;weekdays:TaskWeekday[];reminderEnabled:boolean;reminderMinutes:string;notes:string;medicationName:string;dosage:string;unit:MedicationUnit;customUnit:string;route:MedicationAdministrationRoute;customRoute:string;medicationInstructions:string};
const options=<T extends string>(record:Record<T,string>)=>Object.entries(record).map(([value,label])=>({value:value as T,label:label as string}));
const recurrenceLabels:Record<TaskRecurrenceType,string>={UNICA:'Uma vez',DIARIA:'Diariamente',DIAS_ESPECIFICOS:'Em dias específicos',INTERVALO:'Em intervalo de dias',PERIODO_DETERMINADO:'Durante o período combinado',SEM_DATA_FINAL:'Recorrente'};
const newItem=():DraftItem=>({key:`${Date.now()}-${Math.random()}`,title:'',description:'',category:'ALIMENTACAO',customCategory:'',priority:'NORMAL',recurrenceType:'DIARIA',scheduledTime:'08:00',intervalDays:'2',weekdays:[],reminderEnabled:false,reminderMinutes:'30',notes:'',medicationName:'',dosage:'',unit:'MG',customUnit:'',route:'ORAL',customRoute:'',medicationInstructions:''});
function fromItem(item:CareRoutineItem):DraftItem{return{...newItem(),key:item.id??`${item.sortOrder}`,title:item.title,description:item.description??'',category:item.category??'PERSONALIZADA',customCategory:item.customCategory??(!item.category?'Cuidado anterior':''),priority:item.priority??'NORMAL',recurrenceType:item.recurrenceType??'DIARIA',scheduledTime:(item.scheduledTime??'08:00').slice(0,5),intervalDays:String(item.intervalDays??2),weekdays:item.weekdays??[],reminderEnabled:item.reminderEnabled??false,reminderMinutes:String(item.reminderMinutesBefore??30),notes:item.notes??'',medicationName:item.medication?.name??'',dosage:item.medication?.dosage??'',unit:item.medication?.unit??'MG',customUnit:item.medication?.customUnit??'',route:item.medication?.administrationRoute??'ORAL',customRoute:item.medication?.customAdministrationRoute??'',medicationInstructions:item.medication?.additionalInstructions??''};}

export default function CareRoutineFormScreen(){
  const params=useLocalSearchParams<{id?:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const [name,setName]=useState('');const [description,setDescription]=useState('');const [assistedPersonId,setAssistedPersonId]=useState('GERAL');const [items,setItems]=useState<DraftItem[]>([newItem()]);const [formData,setFormData]=useState<CareRoutineFormData>({assistedPersons:[]});const [loading,setLoading]=useState(Boolean(id));const [saving,setSaving]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);
  useEffect(()=>{let active=true;Promise.all([getCareRoutineFormData(),id?getCareRoutine(id):Promise.resolve(null)]).then(([data,routine])=>{if(!active)return;setFormData(data);if(routine){setName(routine.name);setDescription(routine.description??'');setAssistedPersonId(routine.assistedPerson?.id??'GERAL');setItems(routine.items.map(fromItem));}}).catch(()=>active&&setFeedback('Não foi possível carregar os dados da rotina.')).finally(()=>active&&setLoading(false));return()=>{active=false};},[id]);
  const update=<K extends keyof DraftItem>(key:string,field:K,value:DraftItem[K])=>setItems(current=>current.map(item=>item.key===key?{...item,[field]:value}:item));
  function changeCategory(item:DraftItem,next:TaskCategory){if(item.category===next)return;const apply=()=>setItems(current=>current.map(entry=>entry.key===item.key?{...entry,category:next,customCategory:'',medicationName:'',dosage:'',customUnit:'',customRoute:'',medicationInstructions:''}:entry));if(item.category==='MEDICACAO'&&(item.medicationName||item.dosage||item.medicationInstructions))Alert.alert('Alterar tipo de cuidado','Os campos específicos de medicação serão limpos.',[{text:'Cancelar',style:'cancel'},{text:'Alterar tipo',style:'destructive',onPress:apply}]);else apply();}
  function validate(){if(!name.trim())return'Informe o nome da rotina.';if(!items.length)return'Adicione pelo menos um cuidado.';for(const item of items){if(!item.title.trim())return'Informe o título do cuidado.';if(!item.category)return'Selecione o tipo do cuidado.';if(item.category==='PERSONALIZADA'&&!item.customCategory.trim())return'Informe o nome do tipo de cuidado personalizado.';if(item.recurrenceType==='DIAS_ESPECIFICOS'&&!item.weekdays.length)return'Selecione ao menos um dia da semana para o cuidado.';if(item.recurrenceType==='INTERVALO'&&Number(item.intervalDays)<=0)return'O intervalo do cuidado deve ser maior que zero.';if(item.category==='MEDICACAO'){if(!item.medicationName.trim()||!item.dosage.trim())return'Preencha nome e dosagem do medicamento.';if(item.unit==='PERSONALIZADA'&&!item.customUnit.trim())return'Informe a unidade personalizada.';if(item.route==='OUTRA'&&!item.customRoute.trim())return'Informe a forma de administração personalizada.';}}return null;}
  async function save(){const error=validate();if(error){setFeedback(error);return;}setSaving(true);setFeedback(null);const payload:CareRoutinePayload={name:name.trim(),description:description.trim()||null,assistedPersonId:assistedPersonId==='GERAL'?null:assistedPersonId,items:items.map((item,index)=>({title:item.title.trim(),description:item.description.trim()||null,sortOrder:index+1,category:item.category,customCategory:item.category==='PERSONALIZADA'?item.customCategory.trim():null,priority:item.priority,recurrenceType:item.recurrenceType,scheduledTime:item.scheduledTime,intervalDays:item.recurrenceType==='INTERVALO'?Number(item.intervalDays):null,weekdays:item.recurrenceType==='DIAS_ESPECIFICOS'?item.weekdays:[],reminderEnabled:item.reminderEnabled,reminderMinutesBefore:item.reminderEnabled?Number(item.reminderMinutes):null,notes:item.notes.trim()||null,medication:item.category==='MEDICACAO'?{name:item.medicationName.trim(),dosage:item.dosage.trim(),unit:item.unit,customUnit:item.unit==='PERSONALIZADA'?item.customUnit.trim():undefined,administrationRoute:item.route,customAdministrationRoute:item.route==='OUTRA'?item.customRoute.trim():undefined,additionalInstructions:item.medicationInstructions.trim()||undefined}:null}))};try{const saved=id?await updateCareRoutine(id,payload):await createCareRoutine(payload);router.replace(`/care-task/${saved.id}` as Href);}catch(cause){setFeedback(cause instanceof ApiError?cause.message:'Não foi possível salvar a rotina.');}finally{setSaving(false);}}
  if(loading)return <ScreenContainer contentStyle={styles.center}><Text style={styles.helper}>Carregando rotina...</Text></ScreenContainer>;
  return <ScreenContainer keyboardAvoiding contentStyle={styles.content}><AppHeader showBack backDisabled={saving} title={id?'Editar rotina':'Nova rotina'} subtitle="Organize cuidados completos para reutilizar em solicitações."/><AppTextInput required label="Nome da rotina" icon={FileText} placeholder="Ex.: Cuidados da manhã" value={name} onChangeText={setName}/><AppTextInput optional label="Descrição da rotina" icon={FileText} value={description} onChangeText={setDescription} multiline/><OptionGroup label="Pessoa assistida" value={assistedPersonId} onChange={value=>setAssistedPersonId(value as string)} options={[{value:'GERAL',label:'Rotina geral'},...formData.assistedPersons.map(person=>({value:person.id,label:person.name}))]}/>
    <View style={styles.section}><Text style={styles.sectionTitle}>Cuidados da rotina</Text>{items.map((item,index)=><View key={item.key} style={styles.item}><View style={styles.itemHead}><Text style={styles.itemTitle}>Cuidado {index+1}</Text>{items.length>1?<Pressable accessibilityLabel="Remover cuidado" onPress={()=>setItems(current=>current.filter(entry=>entry.key!==item.key))}><Trash2 size={20} color={colors.destructive}/></Pressable>:null}</View><OptionGroup label="Tipo de cuidado" required options={options(taskCategoryLabels)} value={item.category} onChange={value=>changeCategory(item,value as TaskCategory)}/>{item.category==='PERSONALIZADA'?<AppTextInput label="Nome do tipo de cuidado" required value={item.customCategory} onChangeText={value=>update(item.key,'customCategory',value)}/>:null}<AppTextInput required label="Título do cuidado" icon={FileText} value={item.title} onChangeText={value=>update(item.key,'title',value)}/><AppTextInput optional label="Descrição ou instruções" icon={FileText} value={item.description} onChangeText={value=>update(item.key,'description',value)} multiline/><OptionGroup label="Prioridade" required options={options(taskPriorityLabels)} value={item.priority} onChange={value=>update(item.key,'priority',value as TaskPriority)}/><OptionGroup label="Frequência planejada" required options={options(recurrenceLabels)} value={item.recurrenceType} onChange={value=>update(item.key,'recurrenceType',value as TaskRecurrenceType)}/><TimePickerField label="Horário previsto" required value={item.scheduledTime} onChange={value=>update(item.key,'scheduledTime',value)}/>{item.recurrenceType==='DIAS_ESPECIFICOS'?<OptionGroup label="Dias da semana" required multiple options={options(taskWeekdayLabels)} value={item.weekdays} onChange={value=>update(item.key,'weekdays',value as TaskWeekday[])}/>:null}{item.recurrenceType==='INTERVALO'?<AppTextInput label="Intervalo em dias" required value={item.intervalDays} onChangeText={value=>update(item.key,'intervalDays',value)} keyboardType="number-pad"/>:null}
      {item.category==='MEDICACAO'?<View style={styles.specific}><Text style={styles.specificTitle}>Dados da medicação</Text><Text style={styles.medicalNotice}>Estas informações são cadastradas pelo responsável e não representam prescrição do Cuidar+.</Text><AppTextInput label="Nome do medicamento" required value={item.medicationName} onChangeText={value=>update(item.key,'medicationName',value)}/><AppTextInput label="Dosagem" required value={item.dosage} onChangeText={value=>update(item.key,'dosage',value)}/><OptionGroup label="Unidade" required options={options(medicationUnitLabels)} value={item.unit} onChange={value=>update(item.key,'unit',value as MedicationUnit)}/>{item.unit==='PERSONALIZADA'?<AppTextInput label="Unidade personalizada" required value={item.customUnit} onChangeText={value=>update(item.key,'customUnit',value)}/>:null}<OptionGroup label="Forma de administração" required options={options(medicationRouteLabels)} value={item.route} onChange={value=>update(item.key,'route',value as MedicationAdministrationRoute)}/>{item.route==='OUTRA'?<AppTextInput label="Outra forma de administração" required value={item.customRoute} onChangeText={value=>update(item.key,'customRoute',value)}/>:null}<AppTextInput label="Orientações complementares" optional value={item.medicationInstructions} onChangeText={value=>update(item.key,'medicationInstructions',value)} multiline/></View>:null}
      <OptionGroup label="Planejar lembrete" options={[{value:'SIM',label:'Sim'},{value:'NAO',label:'Não'}]} value={item.reminderEnabled?'SIM':'NAO'} onChange={value=>update(item.key,'reminderEnabled',value==='SIM')}/>{item.reminderEnabled?<AppTextInput label="Antecedência em minutos" required value={item.reminderMinutes} onChangeText={value=>update(item.key,'reminderMinutes',value)} keyboardType="number-pad"/>:null}<AppTextInput label="Observações gerais" optional value={item.notes} onChangeText={value=>update(item.key,'notes',value)} multiline/></View>)}<PrimaryButton variant="secondary" label="Adicionar cuidado" onPress={()=>setItems(current=>[...current,newItem()])}/></View>{feedback?<Text style={styles.error}>{feedback}</Text>:null}<PrimaryButton label={saving?'Salvando rotina...':'Salvar rotina'} loading={saving} disabled={saving} onPress={()=>void save()}/></ScreenContainer>;
}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,justifyContent:'center',alignItems:'center'},section:{gap:spacing.md},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:18,color:colors.foreground},item:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},itemHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},itemTitle:{fontFamily:fontFamily.bold,fontSize:14,color:colors.foreground},specific:{gap:spacing.md,padding:spacing.md,borderRadius:radii.lg,backgroundColor:colors.muted},specificTitle:{fontFamily:fontFamily.extraBold,fontSize:15,color:colors.foreground},medicalNotice:{fontFamily:fontFamily.medium,fontSize:11,lineHeight:17,color:'#665423'},helper:{fontFamily:fontFamily.regular,color:colors.mutedForeground},error:{fontFamily:fontFamily.semiBold,fontSize:13,color:colors.destructive}});
