import { useCallback, useState } from 'react';
import { router, useFocusEffect, type Href } from 'expo-router';
import { ClipboardCheck, RefreshCw } from 'lucide-react-native';
import { Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/app-header';
import { TaskOccurrenceCard } from '@/components/care-task-card';
import { DatePickerField } from '@/components/date-picker-field';
import { OptionGroup } from '@/components/option-group';
import { ScreenContainer } from '@/components/screen-container';
import { getCaregiverDayTasks } from '@/services/careTaskService';
import { colors, fontFamily, radii, spacing } from '@/theme/tokens';
import type { TaskCategory, TaskOccurrence, TaskOccurrenceStatus } from '@/types/careTasks';
import { todayDateOnly } from '@/utils/agendaDate';
import { deviceTimezone, taskCategoryLabels, taskOccurrenceStatusLabels } from '@/utils/careTaskLabels';
import { displayDateToIso, isoDateToDisplay } from '@/utils/contractTerminationLabels';

const filters:(TaskOccurrenceStatus|undefined)[]=[undefined,'PENDENTE','ATRASADA','CONCLUIDA','NAO_REALIZADA'];
export default function CaregiverTasksScreen(){const [date,setDate]=useState(isoDateToDisplay(todayDateOnly()));const [status,setStatus]=useState<TaskOccurrenceStatus>();const [category,setCategory]=useState<TaskCategory|'TODAS'>('TODAS');const [assistedPersonId,setAssistedPersonId]=useState('TODAS');const [people,setPeople]=useState<{value:string;label:string}[]>([]);const [items,setItems]=useState<TaskOccurrence[]|null>(null);const [error,setError]=useState(false);const [refreshing,setRefreshing]=useState(false);
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);setError(false);try{const content=(await getCaregiverDayTasks(displayDateToIso(date),deviceTimezone(),{status,category:category==='TODAS'?undefined:category,assistedPersonId:assistedPersonId==='TODAS'?undefined:assistedPersonId})).content;setItems(content);setPeople(current=>[...new Map([...current,...content.map(item=>({value:item.assistedPersonId,label:item.assistedPersonName}))].map(item=>[item.value,item])).values()]);}catch{setError(true);}finally{setRefreshing(false);}},[assistedPersonId,category,date,status]);useFocusEffect(useCallback(()=>{void load();},[load]));
 return <ScreenContainer contentStyle={styles.content} scrollViewProps={{refreshControl:<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.primary}/>}}><AppHeader showBack title="Tarefas do dia" subtitle="Acompanhe e registre os cuidados da sua rotina."/><DatePickerField label="Data" value={date} onChange={setDate}/><View style={styles.filters}>{filters.map(item=><Pressable key={item??'TODAS'} onPress={()=>setStatus(item)} style={[styles.chip,status===item&&styles.active]}><Text style={[styles.chipText,status===item&&styles.activeText]}>{item?taskOccurrenceStatusLabels[item]:'Todas'}</Text></Pressable>)}</View><View style={styles.advanced}><OptionGroup label="Categoria" options={[{value:'TODAS',label:'Todas'},...Object.entries(taskCategoryLabels).map(([value,label])=>({value:value as TaskCategory,label}))]} value={category} onChange={value=>setCategory(value as TaskCategory|'TODAS')}/>{people.length>1?<OptionGroup label="Pessoa assistida" options={[{value:'TODAS',label:'Todas'},...people]} value={assistedPersonId} onChange={value=>setAssistedPersonId(value as string)}/>:null}</View>
 {items===null&&!error?<State text="Carregando tarefas..."/>:error?<State text="Não foi possível carregar as tarefas." icon={<RefreshCw color={colors.destructive}/>} action={()=>void load()}/>:items?.length===0?<State text="Nenhuma tarefa para esta data." icon={<ClipboardCheck color={colors.primary}/>} />:<View style={styles.list}>{items?.map(item=><TaskOccurrenceCard key={item.id} occurrence={item} onPress={()=>router.push(`/task-occurrence/${item.id}` as Href)}/>)}</View>}</ScreenContainer>}
function State({text,icon,action}:{text:string;icon?:React.ReactNode;action?:()=>void}){return <View style={styles.state}>{icon}<Text style={styles.stateText}>{text}</Text>{action?<Pressable onPress={action}><Text style={styles.retry}>Tentar novamente</Text></Pressable>:null}</View>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},filters:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chip:{minHeight:38,justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radii.full,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},active:{borderColor:colors.primary,backgroundColor:colors.secondary},chipText:{fontFamily:fontFamily.semiBold,fontSize:11,color:colors.mutedForeground},activeText:{color:colors.primary},advanced:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},list:{gap:spacing.md},state:{minHeight:220,alignItems:'center',justifyContent:'center',gap:spacing.md},stateText:{fontFamily:fontFamily.medium,color:colors.mutedForeground},retry:{fontFamily:fontFamily.bold,color:colors.primary}});
