import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { DatePickerField } from '@/components/date-picker-field';
import { OptionGroup } from '@/components/option-group';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { TimePickerField } from '@/components/time-picker-field';
import { ApiError } from '@/services/api';
import { createCareTask, getCareTask, getTaskFormData, optionForTask, updateCareTask } from '@/services/careTaskService';
import { colors, fontFamily, radii, spacing } from '@/theme/tokens';
import type { CareTaskPayload, MedicationAdministrationRoute, MedicationUnit, TaskCategory, TaskContractOption, TaskEditScope, TaskPriority, TaskRecurrenceType, TaskWeekday } from '@/types/careTasks';
import { todayDateOnly } from '@/utils/agendaDate';
import { deviceTimezone, medicationRouteLabels, medicationUnitLabels, taskCategoryLabels, taskPriorityLabels, taskRecurrenceLabels, taskWeekdayLabels } from '@/utils/careTaskLabels';
import { displayDateToIso, isoDateToDisplay } from '@/utils/contractTerminationLabels';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';

const options = <T extends string>(record: Record<T,string>) => Object.entries(record).map(([value,label])=>({value:value as T,label:label as string}));
const editScopeOptions:{value:TaskEditScope;label:string}[]=[{value:'SOMENTE_ESTA_OCORRENCIA',label:'Somente esta ocorrência'},{value:'ESTA_E_FUTURAS',label:'Esta e as próximas'},{value:'TODA_A_SERIE',label:'Toda a série'}];
export default function CareTaskFormScreen(){
  const params=useLocalSearchParams<{id?:string;occurrenceId?:string;occurrenceVersion?:string;scheduledDate?:string;scheduledTime?:string}>(); const id=single(params.id); const occurrenceId=single(params.occurrenceId); const occurrenceVersion=Number(single(params.occurrenceVersion)); const occurrenceDate=single(params.scheduledDate); const occurrenceTime=single(params.scheduledTime); const editing=Boolean(id);
  const [contracts,setContracts]=useState<TaskContractOption[]>([]); const [selected,setSelected]=useState<TaskContractOption>(); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState<TaskCategory>('ALIMENTACAO'); const [customCategory,setCustomCategory]=useState(''); const [priority,setPriority]=useState<TaskPriority>('NORMAL');
  const [recurrenceType,setRecurrenceType]=useState<TaskRecurrenceType>('DIARIA'); const [startDate,setStartDate]=useState(isoDateToDisplay(todayDateOnly())); const [endDate,setEndDate]=useState(''); const [scheduledTime,setScheduledTime]=useState('08:00'); const [intervalDays,setIntervalDays]=useState('2'); const [weekdays,setWeekdays]=useState<TaskWeekday[]>([]);
  const [reminder,setReminder]=useState(false); const [reminderMinutes,setReminderMinutes]=useState('30'); const [notes,setNotes]=useState(''); const [scope,setScope]=useState<TaskEditScope>('TODA_A_SERIE'); const [version,setVersion]=useState(0);
  const [medicationName,setMedicationName]=useState(''); const [dosage,setDosage]=useState(''); const [unit,setUnit]=useState<MedicationUnit>('MG'); const [customUnit,setCustomUnit]=useState(''); const [route,setRoute]=useState<MedicationAdministrationRoute>('ORAL'); const [customRoute,setCustomRoute]=useState(''); const [medicationInstructions,setMedicationInstructions]=useState('');
  useEffect(()=>{(async()=>{try{const form=await getTaskFormData();setContracts(form.contracts);if(id){const detail=await getCareTask(id);const task=detail.task;setSelected(form.contracts.find(item=>item.contractId===task.contractId)??optionForTask(task));setTitle(task.title);setDescription(task.description??'');setCategory(task.category);setCustomCategory(task.customCategory??'');setPriority(task.priority);setRecurrenceType(task.recurrenceType);setStartDate(isoDateToDisplay(occurrenceDate??task.startDate));setEndDate(task.endDate?isoDateToDisplay(task.endDate):'');setScheduledTime((occurrenceTime??task.scheduledTime).slice(0,5));setIntervalDays(String(task.intervalDays??2));setWeekdays(task.weekdays);setReminder(task.reminderEnabled);setReminderMinutes(String(task.reminderMinutesBefore??30));setNotes(task.notes??'');setVersion(task.version);if(detail.medication){setMedicationName(detail.medication.name);setDosage(detail.medication.dosage);setUnit(detail.medication.unit);setCustomUnit(detail.medication.customUnit??'');setRoute(detail.medication.administrationRoute);setCustomRoute(detail.medication.customAdministrationRoute??'');setMedicationInstructions(detail.medication.additionalInstructions??'');}}else setSelected(form.contracts[0]);}catch(error){Alert.alert('Não foi possível carregar o formulário',error instanceof ApiError?error.message:'Tente novamente.');}finally{setLoading(false);}})();},[id,occurrenceDate,occurrenceTime]);
  const medication=useMemo(()=>category==='MEDICACAO'?{name:medicationName.trim(),dosage:dosage.trim(),unit,customUnit:customUnit.trim()||undefined,administrationRoute:route,customAdministrationRoute:customRoute.trim()||undefined,additionalInstructions:medicationInstructions.trim()||undefined}:null,[category,customRoute,customUnit,dosage,medicationInstructions,medicationName,route,unit]);
  async function submit(){if(!selected){Alert.alert('Contratação necessária','Não há contratação ativa selecionada.');return;}if(!title.trim()){Alert.alert('Título obrigatório','Informe o título da tarefa.');return;}if(category==='PERSONALIZADA'&&!customCategory.trim()){Alert.alert('Categoria obrigatória','Informe o nome da categoria personalizada.');return;}if(recurrenceType==='DIAS_ESPECIFICOS'&&!weekdays.length){Alert.alert('Dias obrigatórios','Selecione ao menos um dia da semana.');return;}if(recurrenceType==='PERIODO_DETERMINADO'&&!endDate){Alert.alert('Data final obrigatória','Informe a data final.');return;}if(category==='MEDICACAO'&&(!medicationName.trim()||!dosage.trim())){Alert.alert('Dados do medicamento','Informe nome e dosagem.');return;}const payload:CareTaskPayload={title:title.trim(),description:description.trim()||null,category,customCategory:category==='PERSONALIZADA'?customCategory.trim():null,priority,recurrenceType,startDate:displayDateToIso(startDate),endDate:endDate?displayDateToIso(endDate):null,scheduledTime,intervalDays:recurrenceType==='INTERVALO'?Number(intervalDays):null,weekdays:recurrenceType==='DIAS_ESPECIFICOS'?weekdays:[],timezone:deviceTimezone(),reminderEnabled:reminder,reminderMinutesBefore:reminder?Number(reminderMinutes):null,notes:notes.trim()||null,assistedPersonId:selected.assistedPersonId,contractId:selected.contractId,caregiverId:selected.caregiverId,medication};setSaving(true);try{const result=editing&&id?await updateCareTask(id,{...payload,scope,occurrenceId,occurrenceVersion:Number.isFinite(occurrenceVersion)?occurrenceVersion:undefined,version}):await createCareTask(payload);Alert.alert('Tudo certo',editing?'Tarefa atualizada com sucesso.':'Tarefa criada com sucesso.');router.replace(`/care-task/${result.task.id}` as Href);}catch(error){Alert.alert('Não foi possível salvar',error instanceof ApiError?error.message:'Tente novamente.');}finally{setSaving(false);}}
  if(loading)return <ScreenContainer contentStyle={styles.center}><Text style={styles.muted}>Carregando formulário...</Text></ScreenContainer>;
  return <ScreenContainer contentStyle={styles.content}><AppHeader showBack backDisabled={saving} title={editing?'Editar tarefa':'Nova tarefa'} subtitle="Organize a rotina de cuidado com informações claras."/>
    {editing&&occurrenceId?<Section title="Escopo da alteração"><OptionGroup label="Aplicar alteração em" required options={editScopeOptions} value={scope} onChange={value=>setScope(value as TaskEditScope)}/><Text style={styles.hint}>{scope==='SOMENTE_ESTA_OCORRENCIA'?'Altera somente a data e o horário desta ocorrência.':scope==='ESTA_E_FUTURAS'?'Preserva o histórico e cria uma nova série a partir desta ocorrência.':'Recalcula apenas as ocorrências futuras pendentes.'}</Text></Section>:null}
    <Section title="Identificação"><AppTextInput label="Título" required value={title} onChangeText={setTitle} maxLength={140}/><OptionGroup label="Categoria" required options={options(taskCategoryLabels)} value={category} onChange={value=>setCategory(value as TaskCategory)}/>{category==='PERSONALIZADA'?<AppTextInput label="Nome da categoria" required value={customCategory} onChangeText={setCustomCategory} maxLength={120}/>:null}<OptionGroup label="Prioridade" required options={options(taskPriorityLabels)} value={priority} onChange={value=>setPriority(value as TaskPriority)}/><AppTextInput label="Descrição ou instruções" optional value={description} onChangeText={setDescription} multiline maxLength={2000}/></Section>
    <Section title="Vínculo"><Text style={styles.label}>Contratação ativa *</Text>{contracts.length||selected?<View style={styles.contracts}>{[...(contracts.length?contracts:selected?[selected]:[])].map(item=><Pressable key={item.contractId} onPress={()=>!editing&&setSelected(item)} disabled={editing} style={[styles.contract,selected?.contractId===item.contractId&&styles.contractActive]}><Text style={styles.contractTitle}>{item.assistedPersonName}</Text><Text style={styles.contractText}>Cuidador(a): {item.caregiverName}</Text></Pressable>)}</View>:<Text style={styles.warning}>Nenhuma contratação ativa disponível para cadastrar tarefas.</Text>}</Section>
    <Section title="Agendamento"><OptionGroup label="Recorrência" required options={options(taskRecurrenceLabels)} value={recurrenceType} onChange={value=>setRecurrenceType(value as TaskRecurrenceType)}/><DatePickerField label={recurrenceType==='UNICA'?'Data da tarefa':'Data inicial'} required value={startDate} onChange={setStartDate}/>{recurrenceType!=='UNICA'&&recurrenceType!=='SEM_DATA_FINAL'?<DatePickerField label="Data final" required={recurrenceType==='PERIODO_DETERMINADO'} optional={recurrenceType!=='PERIODO_DETERMINADO'} value={endDate} onChange={setEndDate}/>:null}<TimePickerField label="Horário previsto" required value={scheduledTime} onChange={setScheduledTime}/>{recurrenceType==='DIAS_ESPECIFICOS'?<OptionGroup label="Dias da semana" required multiple options={options(taskWeekdayLabels)} value={weekdays} onChange={value=>setWeekdays(value as TaskWeekday[])}/>:null}{recurrenceType==='INTERVALO'?<AppTextInput label="Intervalo em dias" required value={intervalDays} onChangeText={setIntervalDays} keyboardType="number-pad"/>:null}</Section>
    {category==='MEDICACAO'?<Section title="Medicação"><View style={styles.medicalNotice}><Text style={styles.medicalText}>As informações sobre medicamentos são cadastradas pelos usuários e não representam prescrição ou orientação médica fornecida pelo Cuidar+.</Text></View><AppTextInput label="Nome do medicamento" required value={medicationName} onChangeText={setMedicationName}/><AppTextInput label="Dosagem" required value={dosage} onChangeText={setDosage}/><OptionGroup label="Unidade" required options={options(medicationUnitLabels)} value={unit} onChange={value=>setUnit(value as MedicationUnit)}/>{unit==='PERSONALIZADA'?<AppTextInput label="Unidade personalizada" required value={customUnit} onChangeText={setCustomUnit}/>:null}<OptionGroup label="Forma de administração" required options={options(medicationRouteLabels)} value={route} onChange={value=>setRoute(value as MedicationAdministrationRoute)}/>{route==='OUTRA'?<AppTextInput label="Outra forma de administração" required value={customRoute} onChangeText={setCustomRoute}/>:null}<AppTextInput label="Orientações complementares" optional value={medicationInstructions} onChangeText={setMedicationInstructions} multiline/></Section>:null}
    <Section title="Lembrete"><OptionGroup label="Ativar lembrete" options={[{value:'SIM',label:'Sim'},{value:'NAO',label:'Não'}]} value={reminder?'SIM':'NAO'} onChange={value=>setReminder(value==='SIM')}/>{reminder?<AppTextInput label="Antecedência em minutos" required value={reminderMinutes} onChangeText={setReminderMinutes} keyboardType="number-pad"/>:null}</Section>
    <Section title="Observações"><AppTextInput label="Observações gerais" optional value={notes} onChangeText={setNotes} multiline maxLength={2000}/></Section><PrimaryButton label={editing?'Salvar alterações':'Criar tarefa'} loading={saving} disabled={saving||!selected} onPress={()=>void submit()}/>
  </ScreenContainer>;
}
function single(value?:string|string[]){return Array.isArray(value)?value[0]:value;}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>;}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,alignItems:'center',justifyContent:'center'},muted:{fontFamily:fontFamily.medium,color:colors.mutedForeground},section:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:17,color:colors.foreground},label:{fontFamily:fontFamily.semiBold,fontSize:13,color:colors.foreground},contracts:{gap:spacing.sm},contract:{padding:spacing.md,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.background},contractActive:{borderColor:colors.primary,backgroundColor:colors.secondary},contractTitle:{fontFamily:fontFamily.bold,fontSize:14,color:colors.foreground},contractText:{fontFamily:fontFamily.regular,fontSize:12,color:colors.mutedForeground},warning:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:20,color:colors.destructive},hint:{fontFamily:fontFamily.regular,fontSize:11,lineHeight:17,color:colors.mutedForeground},medicalNotice:{padding:spacing.md,borderRadius:radii.lg,backgroundColor:'#FFF9E5'},medicalText:{fontFamily:fontFamily.medium,fontSize:12,lineHeight:19,color:'#665423'}});
