import { useCallback, useState } from 'react';
import { router, useFocusEffect, useLocalSearchParams, type Href } from 'expo-router';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/app-header';
import { TaskOccurrenceCard } from '@/components/care-task-card';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { TaskPriorityBadge, TaskStatusBadge } from '@/components/task-badges';
import { getCareTask, getTaskOccurrences, taskAction } from '@/services/careTaskService';
import { ApiError } from '@/services/api';
import { colors, fontFamily, radii, spacing } from '@/theme/tokens';
import type { CareTaskDetails, TaskOccurrence } from '@/types/careTasks';
import { addDays, todayDateOnly } from '@/utils/agendaDate';
import { medicationRouteLabels, medicationUnitLabels, taskCategoryName, taskRecurrenceLabels, taskWeekdayLabels } from '@/utils/careTaskLabels';
import { formatDateBR, formatDateTimeLocal, formatScheduleTime } from '@/utils/dateTime';

export default function CareTaskDetailsScreen(){const params=useLocalSearchParams<{id:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const [details,setDetails]=useState<CareTaskDetails>();const [upcoming,setUpcoming]=useState<TaskOccurrence[]>([]);const [history,setHistory]=useState<TaskOccurrence[]>([]);const [error,setError]=useState(false);const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!id)return;setError(false);try{const today=todayDateOnly();const [task,next,previous]=await Promise.all([getCareTask(id),getTaskOccurrences(id,{startDate:today,endDate:addDays(today,59),size:20}),getTaskOccurrences(id,{startDate:addDays(today,-89),endDate:today,history:true,size:20})]);setDetails(task);setUpcoming(next.content);setHistory(previous.content.filter(item=>item.scheduledDate!==today||item.status!=='PENDENTE'));}catch{setError(true);}},[id]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function act(action:'pause'|'reactivate'|'cancel'){if(!details)return;setBusy(true);try{setDetails(await taskAction(details.task.id,action,details.task.version));await load();Alert.alert('Tudo certo',action==='pause'?'Tarefa pausada.':action==='reactivate'?'Tarefa reativada.':'Tarefa cancelada.');}catch(e){Alert.alert('Não foi possível atualizar',e instanceof ApiError?e.message:'Tente novamente.');}finally{setBusy(false);}}
 function confirmCancel(){Alert.alert('Cancelar tarefa?','As ocorrências futuras pendentes serão canceladas. O histórico será preservado.',[{text:'Voltar',style:'cancel'},{text:'Cancelar tarefa',style:'destructive',onPress:()=>void act('cancel')}]);}
 if(error)return <ScreenContainer contentStyle={styles.center}><Text style={styles.error}>Não foi possível carregar a tarefa.</Text><PrimaryButton label="Tentar novamente" onPress={()=>void load()}/></ScreenContainer>;if(!details)return <ScreenContainer contentStyle={styles.center}><Text style={styles.muted}>Carregando tarefa...</Text></ScreenContainer>;const {task,medication}=details;
 return <ScreenContainer contentStyle={styles.content}><AppHeader showBack backDisabled={busy} title={task.title} subtitle={taskCategoryName(task.category,task.customCategory)}/><View style={styles.badges}><TaskStatusBadge status={task.status}/><TaskPriorityBadge priority={task.priority}/></View>
  <Section title="Rotina"><Info label="Pessoa assistida" value={task.assistedPersonName}/><Info label="Cuidador(a)" value={task.caregiverName}/><Info label="Recorrência" value={taskRecurrenceLabels[task.recurrenceType]}/><Info label="Data inicial" value={formatDateBR(task.startDate)}/>{task.endDate?<Info label="Data final" value={formatDateBR(task.endDate)}/>:null}<Info label="Horário" value={formatScheduleTime(task.scheduledTime)}/>{task.weekdays.length?<Info label="Dias" value={task.weekdays.map(day=>taskWeekdayLabels[day]).join(', ')}/>:null}{task.description?<Info label="Instruções" value={task.description}/>:null}{task.notes?<Info label="Observações" value={task.notes}/>:null}<Info label="Lembrete" value={task.reminderEnabled?`${task.reminderMinutesBefore} minutos antes`:'Desativado'}/></Section>
  {medication?<Section title="Medicação"><View style={styles.notice}><Text style={styles.noticeText}>As informações sobre medicamentos são cadastradas pelos usuários e não representam prescrição ou orientação médica fornecida pelo Cuidar+.</Text></View><Info label="Medicamento" value={medication.name}/><Info label="Dosagem" value={`${medication.dosage} · ${medication.unit==='PERSONALIZADA'?medication.customUnit:medicationUnitLabels[medication.unit]}`}/><Info label="Administração" value={medication.administrationRoute==='OUTRA'?medication.customAdministrationRoute??'Outra':medicationRouteLabels[medication.administrationRoute]}/>{medication.additionalInstructions?<Info label="Orientações" value={medication.additionalInstructions}/>:null}</Section>:null}
  {task.status==='ATIVA'||task.status==='PAUSADA'?<Section title="Ações"><PrimaryButton label="Editar tarefa" variant="secondary" disabled={busy} onPress={()=>router.push(`/care-task-form?id=${task.id}` as Href)}/>{task.status==='ATIVA'?<PrimaryButton label="Pausar tarefa" variant="secondary" disabled={busy} onPress={()=>void act('pause')}/>:<PrimaryButton label="Reativar tarefa" disabled={busy} onPress={()=>void act('reactivate')}/>}<PrimaryButton label="Cancelar tarefa" variant="secondary" disabled={busy} onPress={confirmCancel}/></Section>:null}
  <Section title="Próximas ocorrências">{upcoming.length?upcoming.map(item=><TaskOccurrenceCard key={item.id} occurrence={item} onPress={()=>router.push(`/task-occurrence/${item.id}` as Href)}/>):<Text style={styles.muted}>Nenhuma ocorrência futura.</Text>}</Section>
  <Section title="Histórico recente">{history.length?history.map(item=><TaskOccurrenceCard key={item.id} occurrence={item} onPress={()=>router.push(`/task-occurrence/${item.id}` as Href)}/>):<Text style={styles.muted}>Nenhuma ocorrência no histórico.</Text>}</Section>
  <Section title="Atualizações">{details.audit.length?details.audit.map(item=><View key={item.id} style={styles.audit}><Text style={styles.auditTitle}>{auditLabel(item.action)}</Text><Text style={styles.auditText}>{item.actorName} · {formatDateTimeLocal(item.createdAt)}</Text>{item.details?<Text style={styles.auditText}>{item.details}</Text>:null}</View>):<Text style={styles.muted}>Sem atualizações registradas.</Text>}</Section>
 </ScreenContainer>}
function auditLabel(action:string){return ({CRIADA:'Tarefa criada',ALTERADA:'Tarefa alterada',PAUSADA:'Tarefa pausada',REATIVADA:'Tarefa reativada',CANCELADA:'Tarefa cancelada',OCORRENCIA_ALTERADA:'Ocorrência alterada',OCORRENCIA_CANCELADA:'Ocorrência cancelada',OCORRENCIA_CONCLUIDA:'Ocorrência concluída',OCORRENCIA_NAO_REALIZADA:'Ocorrência não realizada'} as Record<string,string>)[action]??'Atualização';}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}function Info({label,value}:{label:string;value:string}){if(!value)return null;return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,gap:spacing.lg},center:{flexGrow:1,alignItems:'center',justifyContent:'center',gap:spacing.md,padding:spacing.xl},error:{fontFamily:fontFamily.bold,color:colors.destructive},muted:{fontFamily:fontFamily.regular,fontSize:12,lineHeight:18,color:colors.mutedForeground},badges:{flexDirection:'row',gap:spacing.sm},section:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:17,color:colors.foreground},info:{gap:spacing.xxs},infoLabel:{fontFamily:fontFamily.semiBold,fontSize:11,color:colors.mutedForeground},infoValue:{fontFamily:fontFamily.medium,fontSize:13,lineHeight:20,color:colors.foreground},notice:{padding:spacing.md,borderRadius:radii.lg,backgroundColor:'#FFF9E5'},noticeText:{fontFamily:fontFamily.medium,fontSize:12,lineHeight:19,color:'#665423'},audit:{gap:spacing.xxs,paddingBottom:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.border},auditTitle:{fontFamily:fontFamily.bold,fontSize:13,color:colors.foreground},auditText:{fontFamily:fontFamily.regular,fontSize:11,lineHeight:17,color:colors.mutedForeground}});
