import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, FileClock, Filter, Search, X } from 'lucide-react-native';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppHeader } from '@/components/app-header';
import { AppTextInput } from '@/components/app-text-input';
import { DatePickerField } from '@/components/date-picker-field';
import { LoadingState } from '@/components/loading-state';
import { PrimaryButton } from '@/components/primary-button';
import { ScreenContainer } from '@/components/screen-container';
import { ApiError } from '@/services/api';
import { getAudit, listAudit } from '@/services/adminService';
import { colors, fontFamily, radii, shadows, spacing } from '@/theme/tokens';
import type { AuditCategory, AuditDetails, AuditFilters, AuditPage, AuditResult, AuditSummary } from '@/types/admin';

type Choice = { value:string; label:string };
const categoryOptions:Choice[]=[{value:'',label:'Todas as categorias'},{value:'SEGURANCA',label:'Segurança'},{value:'ADMINISTRATIVO',label:'Administrativo'},{value:'PRIVACIDADE',label:'Privacidade'},{value:'CONTRATACAO',label:'Contratação'},{value:'ASSISTENCIAL',label:'Assistencial'},{value:'ATENDIMENTO',label:'Atendimento'},{value:'RELATORIO',label:'Relatório'}];
const resultOptions:Choice[]=[{value:'',label:'Todos os resultados'},{value:'SUCESSO',label:'Sucesso'},{value:'FALHA',label:'Falha'},{value:'BLOQUEADO_POR_REGRA',label:'Bloqueado por regra'}];
const actionOptions:Choice[]=[
  {value:'',label:'Todas as ações'},
  ['LOGIN_SUCESSO','Login realizado'],['LOGIN_BLOQUEADO','Login bloqueado'],['RECUPERACAO_SENHA_SOLICITADA','Recuperação de senha solicitada'],['SENHA_REDEFINIDA','Senha redefinida'],
  ['REAUTENTICACAO_EXCLUSAO','Identidade confirmada para exclusão'],['CONTA_EXCLUSAO_SOLICITADA','Exclusão de conta solicitada'],['CONTA_EXCLUIDA','Conta excluída'],['DADOS_ANONIMIZADOS','Dados anonimizados'],['SESSOES_REVOGADAS','Sessões e tokens revogados'],
  ['CONSULTA_USUARIO','Detalhes de usuário consultados'],['CONSULTA_CUIDADOR','Detalhes de cuidador consultados'],['CONSULTA_RESPONSAVEL','Detalhes de responsável consultados'],['USUARIO_BLOQUEADO','Usuário bloqueado'],['USUARIO_DESBLOQUEADO','Usuário desbloqueado'],
  ['CUIDADOR_APROVADO','Cuidador aprovado'],['CUIDADOR_REPROVADO','Cuidador reprovado'],['CUIDADOR_BLOQUEADO','Cuidador bloqueado'],['RESPONSAVEL_APROVADO','Responsável aprovado'],['RESPONSAVEL_REPROVADO','Responsável reprovado'],['RESPONSAVEL_BLOQUEADO','Responsável bloqueado'],
  ['SOLICITACAO_SERVICO_CRIADA','Solicitação de serviço criada'],['SOLICITACAO_SERVICO_ACEITA','Solicitação de serviço aceita'],['SOLICITACAO_SERVICO_REJEITADA','Solicitação de serviço rejeitada'],['SOLICITACAO_SERVICO_CANCELADA','Solicitação de serviço cancelada'],['SOLICITACAO_SERVICO_EXPIRADA','Solicitação de serviço expirada'],
  ['CONTRATACAO_CRIADA','Contratação criada'],['CONTRATACAO_ENCERRAMENTO_AGENDADO','Encerramento de contratação agendado'],['CONTRATACAO_ENCERRADA','Contratação encerrada'],['CONTRATACAO_CANCELADA','Contratação cancelada'],['CONTRATACAO_STATUS_ALTERADO','Situação da contratação alterada'],
  ['ROTINA_CUIDADO_CRIADA','Rotina de cuidado criada'],['ROTINA_CUIDADO_ALTERADA','Rotina de cuidado alterada'],['ROTINA_CUIDADO_INATIVADA','Rotina de cuidado inativada'],['ROTINA_CUIDADO_REATIVADA','Rotina de cuidado reativada'],
  ['TAREFA_CUIDADO_CRIADA','Tarefa de cuidado criada'],['TAREFA_CUIDADO_ALTERADA','Tarefa de cuidado alterada'],['TAREFA_CUIDADO_INATIVADA','Tarefa de cuidado inativada'],['TAREFA_CUIDADO_REATIVADA','Tarefa de cuidado reativada'],
  ['OCORRENCIA_CUIDADO_ALTERADA','Ocorrência de cuidado alterada'],['OCORRENCIA_CUIDADO_CANCELADA','Ocorrência de cuidado cancelada'],['OCORRENCIA_CUIDADO_CONCLUIDA','Ocorrência de cuidado concluída'],['OCORRENCIA_CUIDADO_NAO_REALIZADA','Ocorrência de cuidado não realizada'],
  ['REGISTRO_DIARIO_CRIADO','Registro de diário criado'],['FOTO_ASSISTENCIAL_ENVIADA','Foto assistencial enviada'],['PERFIL_ALTERADO','Perfil alterado'],['ATENDIMENTO_INICIADO','Atendimento iniciado'],['ATENDIMENTO_ENCERRADO','Atendimento encerrado'],
  ['RELATORIO_GERADO','Relatório gerado'],['RELATORIO_EDITADO','Relatório editado'],['RELATORIO_FINALIZADO','Relatório finalizado'],['RELATORIO_EMAIL_ENVIADO','Relatório enviado por e-mail'],['RELATORIO_EMAIL_FALHOU','Falha no envio do relatório por e-mail'],
].map(item=>Array.isArray(item)?{value:item[0],label:item[1]}:item);
const entityOptions:Choice[]=[{value:'',label:'Todas as entidades'},{value:'USUARIO',label:'Usuário'},{value:'CUIDADOR',label:'Cuidador'},{value:'RESPONSAVEL',label:'Responsável'},{value:'PESSOA_ASSISTIDA',label:'Pessoa assistida'},{value:'SOLICITACAO_SERVICO',label:'Solicitação de serviço'},{value:'CONTRATACAO',label:'Contratação'},{value:'ROTINA_CUIDADO',label:'Rotina de cuidado'},{value:'TAREFA_CUIDADO',label:'Tarefa de cuidado'},{value:'OCORRENCIA_CUIDADO',label:'Ocorrência de cuidado'},{value:'REGISTRO_DIARIO_CUIDADO',label:'Registro de diário'},{value:'REGISTRO_ATENDIMENTO',label:'Registro de atendimento'},{value:'RELATORIO_ATENDIMENTO',label:'Relatório de atendimento'}];
const entityLabels=Object.fromEntries(entityOptions.map(item=>[item.value,item.label]));
const statusLabels:Record<string,string>={ATIVO:'Ativo',BLOQUEADO:'Bloqueado',INATIVO:'Inativo',EXCLUIDO:'Excluído',PENDENTE:'Pendente',APROVADO:'Aprovado',REPROVADO:'Reprovado',ABERTA:'Aberta',ACEITA:'Aceita',REJEITADA:'Rejeitada',CANCELADA:'Cancelada',EXPIRADA:'Expirada',AGENDADA:'Agendada',ATIVA:'Ativa',ENCERRAMENTO_AGENDADO:'Encerramento agendado',ENCERRADA:'Encerrada',FINALIZADA:'Finalizada',true:'Sim',false:'Não'};

function apiInstant(value:string,end=false){if(!value)return undefined;const [day,month,year]=value.split('/').map(Number);if(!day||!month||!year)return undefined;const date=new Date(year,month-1,day,end?23:0,end?59:0,end?59:0,end?999:0);return date.toISOString();}
function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));}
function summaryText(value?:Record<string,string>|null){if(!value)return 'Não informado';return Object.entries(value).map(([key,item])=>`${key==='situacaoConta'?'Situação da conta':key==='situacaoAprovacao'?'Situação da aprovação':key==='ativo'?'Ativo':'Situação'}: ${statusLabels[item]??item}`).join(' · ');}

export default function AdminAuditScreen(){
  const [data,setData]=useState<AuditPage|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [details,setDetails]=useState<AuditDetails|null>(null);const [detailsLoading,setDetailsLoading]=useState(false);
  const [action,setAction]=useState('');const [category,setCategory]=useState('');const [result,setResult]=useState('');const [entityType,setEntityType]=useState('');const [actorId,setActorId]=useState('');const [entityId,setEntityId]=useState('');const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');const [page,setPage]=useState(0);const [version,setVersion]=useState(0);
  const filters=useMemo<AuditFilters>(()=>({action:action||undefined,category:(category||undefined) as AuditCategory|undefined,result:(result||undefined) as AuditResult|undefined,responsibleUserId:actorId.trim()||undefined,affectedEntityType:entityType||undefined,affectedEntityId:entityId.trim()||undefined,start:apiInstant(startDate),end:apiInstant(endDate,true),page,size:20}),[action,category,result,actorId,entityType,entityId,startDate,endDate,page]);
  useEffect(()=>{let active=true;setLoading(true);setError(null);listAudit(filters).then(value=>active&&setData(value)).catch(cause=>active&&setError(cause instanceof ApiError?cause.message:'Não foi possível carregar a auditoria.')).finally(()=>active&&setLoading(false));return()=>{active=false};},[filters,version]);
  function clear(){setAction('');setCategory('');setResult('');setEntityType('');setActorId('');setEntityId('');setStartDate('');setEndDate('');setPage(0);setVersion(value=>value+1);}
  async function open(item:AuditSummary){setDetailsLoading(true);setError(null);try{setDetails(await getAudit(item.id));}catch(cause){setError(cause instanceof ApiError?cause.message:'Não foi possível abrir o registro.');}finally{setDetailsLoading(false);}}
  return <ScreenContainer contentStyle={styles.content}><AppHeader title="Auditoria" subtitle="Ações críticas registradas pela plataforma."/>
    <View style={styles.filters}><Text style={styles.sectionTitle}><Filter size={18} color={colors.admin}/> Filtros</Text><Selector label="Tipo de ação" value={action} options={actionOptions} onChange={value=>{setAction(value);setPage(0)}}/><Selector label="Categoria" value={category} options={categoryOptions} onChange={value=>{setCategory(value);setPage(0)}}/><Selector label="Resultado" value={result} options={resultOptions} onChange={value=>{setResult(value);setPage(0)}}/><Selector label="Entidade afetada" value={entityType} options={entityOptions} onChange={value=>{setEntityType(value);setPage(0)}}/>
      <AppTextInput optional label="ID do usuário responsável" icon={Search} value={actorId} onChangeText={value=>{setActorId(value);setPage(0)}} autoCapitalize="none"/><AppTextInput optional label="ID da entidade afetada" icon={Search} value={entityId} onChangeText={value=>{setEntityId(value);setPage(0)}} autoCapitalize="none"/>
      <View style={styles.dateRow}><View style={styles.grow}><DatePickerField optional label="De" value={startDate} onChange={value=>{setStartDate(value);setPage(0)}}/></View><View style={styles.grow}><DatePickerField optional label="Até" value={endDate} onChange={value=>{setEndDate(value);setPage(0)}}/></View></View><PrimaryButton variant="secondary" icon={X} label="Limpar filtros" onPress={clear}/></View>
    {error?<Text style={styles.error}>{error}</Text>:null}{loading||detailsLoading?<LoadingState message={detailsLoading?'Abrindo registro...':'Carregando auditoria...'}/>:null}
    {!loading&&data?.content.length===0?<View style={styles.empty}><FileClock size={32} color={colors.admin}/><Text style={styles.emptyTitle}>Nenhum evento encontrado</Text><Text style={styles.meta}>Ajuste os filtros ou consulte outro período.</Text></View>:null}
    {!loading?<View style={styles.list}>{data?.content.map(item=><AuditCard key={item.id} item={item} onPress={()=>void open(item)}/>)}</View>:null}
    {data&&data.totalPages>0?<View style={styles.pagination}><Pressable disabled={page===0||loading} onPress={()=>setPage(value=>Math.max(0,value-1))} style={[styles.pageButton,(page===0||loading)&&styles.disabled]}><ChevronLeft size={18} color={colors.primary}/><Text style={styles.pageText}>Anterior</Text></Pressable><Text style={styles.meta}>Página {data.page+1} de {data.totalPages}</Text><Pressable disabled={page+1>=data.totalPages||loading} onPress={()=>setPage(value=>value+1)} style={[styles.pageButton,(page+1>=data.totalPages||loading)&&styles.disabled]}><Text style={styles.pageText}>Próxima</Text><ChevronRight size={18} color={colors.primary}/></Pressable></View>:null}
    <AuditDetail value={details} onClose={()=>setDetails(null)}/>
  </ScreenContainer>;
}

function AuditCard({item,onPress}:{item:AuditSummary;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.row}><View style={styles.grow}><Text style={styles.cardTitle}>{item.actionLabel}</Text><Text style={styles.meta}>{item.categoryLabel} · {item.resultLabel}</Text></View><CalendarDays size={19} color={colors.admin}/></View><Text style={styles.meta}>Responsável: {item.responsibleUserName}</Text><Text style={styles.meta}>{item.affectedEntityType?`${entityLabels[item.affectedEntityType]??'Entidade'} · ${item.affectedEntityId??'sem identificação'}`:'Sem entidade associada'}</Text><Text style={styles.date}>{formatDate(item.createdAt)}</Text></Pressable>}
function Selector({label,value,options,onChange}:{label:string;value:string;options:Choice[];onChange:(value:string)=>void}){const [open,setOpen]=useState(false);const selected=options.find(item=>item.value===value)??options[0];return <><View style={styles.selectorWrap}><Text style={styles.label}>{label}</Text><Pressable onPress={()=>setOpen(true)} style={styles.selector}><Text style={styles.selectorText}>{selected.label}</Text><ChevronDown size={18} color={colors.mutedForeground}/></Pressable></View><Modal transparent visible={open} animationType="fade" onRequestClose={()=>setOpen(false)}><View style={styles.backdrop}><View style={styles.modal}><View style={styles.modalHead}><Text style={styles.modalTitle}>{label}</Text><Pressable accessibilityLabel="Fechar" onPress={()=>setOpen(false)}><X size={22} color={colors.foreground}/></Pressable></View><ScrollView contentContainerStyle={styles.choices}>{options.map(item=><Pressable key={item.value||'ALL'} onPress={()=>{onChange(item.value);setOpen(false)}} style={[styles.choice,item.value===value&&styles.choiceSelected]}><Text style={[styles.choiceText,item.value===value&&styles.choiceTextSelected]}>{item.label}</Text></Pressable>)}</ScrollView></View></View></Modal></>}
function AuditDetail({value,onClose}:{value:AuditDetails|null;onClose:()=>void}){return <Modal transparent visible={Boolean(value)} animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.modal}><View style={styles.modalHead}><Text style={styles.modalTitle}>Detalhe da auditoria</Text><Pressable accessibilityLabel="Fechar" onPress={onClose}><X size={22} color={colors.foreground}/></Pressable></View>{value?<ScrollView contentContainerStyle={styles.detail}><Info label="Operação" value={value.actionLabel}/><Info label="Categoria" value={value.categoryLabel}/><Info label="Resultado" value={value.resultLabel}/><Info label="Usuário responsável" value={value.responsibleUser?.name??'Sistema'}/><Info label="Momento" value={formatDate(value.createdAt)}/><Info label="Entidade afetada" value={value.affectedEntityType?`${entityLabels[value.affectedEntityType]??'Entidade'} · ${value.affectedEntityId??'sem identificação'}`:'Não informada'}/>{value.relatedEntityType?<Info label="Entidade relacionada" value={`${entityLabels[value.relatedEntityType]??'Entidade'} · ${value.relatedEntityId??'sem identificação'}`}/>:null}<Info label="Valor anterior resumido" value={summaryText(value.previousSummary)}/><Info label="Novo valor resumido" value={summaryText(value.newSummary)}/>{value.reason?<Info label="Motivo resumido" value={value.reason}/>:null}{value.summaryMessage?<Info label="Mensagem resumida" value={value.summaryMessage}/>:null}</ScrollView>:null}</View></View></Modal>}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}

const styles=StyleSheet.create({content:{paddingHorizontal:spacing.xl,paddingBottom:spacing.xxl+72,gap:spacing.lg},filters:{gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},sectionTitle:{fontFamily:fontFamily.extraBold,fontSize:16,color:colors.foreground},selectorWrap:{gap:spacing.xs},label:{fontFamily:fontFamily.semiBold,fontSize:13,color:colors.foreground},selector:{minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md,paddingHorizontal:spacing.lg,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.background},selectorText:{flex:1,fontFamily:fontFamily.medium,fontSize:14,color:colors.foreground},dateRow:{flexDirection:'row',gap:spacing.sm},grow:{flex:1,minWidth:0},list:{gap:spacing.md},card:{gap:spacing.sm,padding:spacing.lg,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,...shadows.card},row:{flexDirection:'row',alignItems:'flex-start',gap:spacing.md},cardTitle:{fontFamily:fontFamily.bold,fontSize:15,color:colors.foreground},meta:{fontFamily:fontFamily.regular,fontSize:12,lineHeight:18,color:colors.mutedForeground},date:{fontFamily:fontFamily.semiBold,fontSize:12,color:colors.admin},error:{fontFamily:fontFamily.medium,fontSize:13,color:colors.destructive},empty:{alignItems:'center',gap:spacing.sm,padding:spacing.xl},emptyTitle:{fontFamily:fontFamily.bold,fontSize:16,color:colors.foreground},pagination:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},pageButton:{minHeight:42,flexDirection:'row',alignItems:'center',gap:spacing.xs,paddingHorizontal:spacing.md,borderRadius:radii.lg,backgroundColor:colors.secondary},pageText:{fontFamily:fontFamily.bold,fontSize:12,color:colors.primary},disabled:{opacity:.45},pressed:{opacity:.8},backdrop:{flex:1,justifyContent:'center',padding:spacing.xl,backgroundColor:'rgba(15, 23, 42, 0.55)'},modal:{maxHeight:'84%',gap:spacing.md,padding:spacing.lg,borderRadius:radii.xl,backgroundColor:colors.card},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},modalTitle:{fontFamily:fontFamily.extraBold,fontSize:18,color:colors.foreground},choices:{gap:spacing.xs,paddingBottom:spacing.md},choice:{minHeight:46,justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radii.md},choiceSelected:{backgroundColor:colors.secondary},choiceText:{fontFamily:fontFamily.medium,fontSize:13,color:colors.foreground},choiceTextSelected:{fontFamily:fontFamily.bold,color:colors.primary},detail:{gap:spacing.md,paddingBottom:spacing.lg},info:{gap:spacing.xxs},infoLabel:{fontFamily:fontFamily.bold,fontSize:12,color:colors.mutedForeground},infoValue:{fontFamily:fontFamily.medium,fontSize:14,lineHeight:21,color:colors.foreground}});
